
[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.99
title = "Alacritty"

[window.padding]
x = 15
y = 15

[general]
import = ['C:\Users\MORENOC0\AppData/Roaming/alacritty/mocha.toml']
