;;; writing-checks-test.el --- tests for config.org's WRITING CHECKs  -*- lexical-binding: t; -*-
;;
;; Run by run.sh, which cuts the WRITING CHECKs section out of the tangled
;; config.el:  emacs --batch -Q -l writing-checks-test.el MODULE.el </dev/null
;; Doom's packages come from its straight build directory; Doom itself is not
;; loaded, so `doom-user-dir' and `map!' get stand-ins below.
(defvar test-build-dir
  (expand-file-name (format "~/.config/emacs/.local/straight/build-%s/" emacs-version)))
(setq load-path (append (directory-files test-build-dir t "\\`[^.]") load-path))
(load (expand-file-name "jinx/jinx-autoloads.el" test-build-dir) nil t)
(defvar doom-user-dir (expand-file-name "~/.config/doom/"))
(defmacro map! (&rest _) "Doom's key binder; the tests press no leader keys." nil)
(require 'cl-lib)
(require 'flycheck)
(require 'gptel)
(require 'gptel-openai)
(load (car command-line-args-left) nil t)
(setq command-line-args-left nil)
(setq kyo/prose-ai-engine 'gptel)        ; the gptel tests; M lets Claude answer

(defvar test-dir (file-name-directory load-file-name))
(defvar test-failures 0)

(defun test-check (name ok &optional detail)
  (unless ok (setq test-failures (1+ test-failures)))
  (princ (format "%s  %s%s\n" (if ok "PASS" "FAIL") name (if detail (format "  [%s]" detail) ""))))

(defun test-buffer ()
  "A fresh org buffer with three misspellings, jinx on."
  (let ((buf (get-buffer-create "*quick-test*")))
    (with-current-buffer buf
      (erase-buffer)
      (insert "- A mispeled word, a wrng word and a thrid one.\n")
      (org-mode)
      (setq jinx-languages "en_US es_CO")
      (font-lock-ensure)
      (jinx-mode 1)
      (jinx--check-region (point-min) (point-max)))
    buf))

(defun test-goto (word)
  (goto-char (point-min)) (search-forward word) (backward-char 2))

;; A. numbering matches the card, past kyo/prose-card-max too
(let* ((fix (lambda (s) (list s 'replace s)))
       (issues (list (list :level 'error :kind "Grammar" :message "A" :beg 1 :end 2
                           :fixes (mapcar fix '("a1" "a2" "a3" "a4" "a5" "a6" "a7")))
                     (list :level 'warning :kind "Style" :message "B" :beg 1 :end 2
                           :fixes (mapcar fix '("b1" "b2"))))))
  (cl-letf (((symbol-function 'kyo/prose--issues-at) (lambda (_pos) issues)))
    (with-temp-buffer
      (let* ((lists (kyo/prose--fix-list 1))
             (card (kyo/prose--card-text issues))
             (card-nums (let (out (start 0))
                          (while (string-match "^ +\\([0-9]+\\)  \\(.*[^ ]\\) *$" card start)
                            (push (cons (string-to-number (match-string 1 card)) (match-string-no-properties 2 card)) out)
                            (setq start (match-end 0)))
                          (nreverse out)))
             (list-nums (seq-map-indexed (lambda (entry i)
                                           (cons (1+ i) (replace-regexp-in-string "\\`[0-9]+  [A-Za-z ]+: " "" (car entry))))
                                         (nth 0 lists))))
        (test-check "A1 seven numbered fixes (5 + 2), two more" (and (= (length (nth 0 lists)) 7) (= (length (nth 1 lists)) 2))
                    (format "%d/%d" (length (nth 0 lists)) (length (nth 1 lists))))
        (test-check "A2 card numbers = list numbers" (equal card-nums list-nums) (format "%S" card-nums))
        (test-check "A3 the extra fixes are a6 a7, unnumbered" (equal (mapcar #'car (nth 1 lists)) '("   Grammar: a6" "   Grammar: a7")))
        (test-check "A4 footer names z= and the number" (string-match-p "type z= and its number" card))))))

;; B. z=1 typed fast applies fix 1 without the list
(with-current-buffer (test-buffer)
  (test-goto "mispeled")
  (let* ((first (car (car (kyo/prose--fix-list (point)))))
         (picker-opened nil))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (setq picker-opened t) (car first))))
      (setq unread-command-events (list ?1))
      (kyo/prose-fix-at-point))
    (test-check "B1 z=1 applied fix 1" (string-match-p "misspelled" (buffer-string)) (buffer-string))
    (test-check "B2 no list opened" (not picker-opened))
    (test-check "B3 the 1 was consumed" (null unread-command-events))))

;; C. 2z= (count first, Vim style) applies fix 2 without waiting
(with-current-buffer (test-buffer)
  (test-goto "wrng")
  (let* ((second (cdr (nth 1 (car (kyo/prose--fix-list (point))))))
         (waited nil))
    (cl-letf (((symbol-function 'read-event) (lambda (&rest _) (setq waited t) nil)))
      (kyo/prose-fix-at-point 2))
    (test-check "C1 2z= applied fix 2" (string-match-p (regexp-quote (plist-get second :arg)) (buffer-string))
                (format "%s -> %s" (plist-get second :arg) (buffer-string)))
    (test-check "C2 no wait for a digit" (not waited))))

;; D. mouse motion between z= and the digit does not count
(with-current-buffer (test-buffer)
  (test-goto "thrid")
  (let ((first (cdr (car (car (kyo/prose--fix-list (point)))))))
    (setq unread-command-events (list '(mouse-movement nil) '(mouse-movement nil) ?1))
    (kyo/prose-fix-at-point)
    (test-check "D1 z= <mouse moves> 1 applied fix 1" (string-match-p (regexp-quote (plist-get first :arg)) (buffer-string))
                (format "%s -> %s" (plist-get first :arg) (buffer-string)))))

;; E. another key: goes back on the input and the list opens
(with-current-buffer (test-buffer)
  (test-goto "mispeled")
  (let (seen-unread seen-labels)
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt collection &rest _)
                 (setq seen-unread unread-command-events
                       seen-labels (all-completions "" collection))
                 (setq unread-command-events nil)
                 (nth 1 seen-labels))))
      (setq unread-command-events (list ?x))
      (kyo/prose-fix-at-point))
    (test-check "E1 the x went back on the input" (equal seen-unread '(?x)) (format "%S" seen-unread))
    (test-check "E2 the list shows the card's numbers" (string-prefix-p "1  Spelling: " (car seen-labels)) (car seen-labels))
    (test-check "E3 choosing from the list applied it" (not (string-match-p "mispeled" (buffer-string))) (buffer-string))))

;; F. a pause (read-event times out) opens the list
(with-current-buffer (test-buffer)
  (test-goto "wrng")
  (let (opened)
    (cl-letf (((symbol-function 'read-event) (lambda (&rest _) nil))
              ((symbol-function 'completing-read) (lambda (&rest _) (setq opened t) (signal 'quit nil))))
      (condition-case nil (kyo/prose-fix-at-point) (quit nil)))
    (test-check "F1 pausing opens the list" opened)
    (test-check "F2 quitting the list leaves the text alone" (string-match-p "wrng" (buffer-string)))))

;; G. a card on screen wins over point, a stale one does not
(with-current-buffer (test-buffer)
  (let ((card-pos (progn (test-goto "thrid") (point))))
    (goto-char (point-min))
    (setq kyo/prose--card (list (current-buffer) (point) (buffer-chars-modified-tick) 'mouse card-pos))
    (test-check "G1 card-pos is the card's underline" (eql (kyo/prose--card-pos) card-pos))
    (setq unread-command-events (list ?1))
    (kyo/prose-fix-at-point)
    (test-check "G2 z=1 fixed the mouse card's word, not point's" (not (string-match-p "thrid" (buffer-string))) (buffer-string))
    (setq kyo/prose--card (list (current-buffer) (1+ (point)) (buffer-chars-modified-tick) 'mouse card-pos))
    (test-check "G3 a card whose point moved is stale" (null (kyo/prose--card-pos)))
    (setq kyo/prose--card nil)))

;; H. the local-server check
(let ((down (gptel-make-openai "Test Down" :host "localhost:4100" :protocol "http" :key "x" :models '(m)))
      (remote (gptel-make-openai "Test Remote" :host "api.example.invalid" :key "x" :models '(m)))
      (srv (make-network-process :name "kyo-test-srv" :server t :host "127.0.0.1" :service t :family 'ipv4)))
  (let ((up (gptel-make-openai "Test Up" :host (format "localhost:%d" (process-contact srv :service))
                               :protocol "http" :key "x" :models '(m)))
        (up4 (gptel-make-openai "Test Up4" :host (format "127.0.0.1:%d" (process-contact srv :service))
                                :protocol "http" :key "x" :models '(m))))
    (test-check "H1 nothing on localhost:4100 is down" (kyo/prose--gptel-down-p down))
    (test-check "H2 a listening localhost server is up" (not (kyo/prose--gptel-down-p up)))
    (test-check "H3 a listening 127.0.0.1 server is up" (not (kyo/prose--gptel-down-p up4)))
    (test-check "H4 remote hosts are left to gptel" (not (kyo/prose--gptel-down-p remote))))
  (delete-process srv))

;; I. proofread names the dead server instead of sending anything
(with-temp-buffer
  (org-mode)
  (insert "Some text to check.")
  (transient-mark-mode 1)
  (set-mark (point-min)) (goto-char (point-max)) (activate-mark)
  (let ((gptel-backend (gptel-make-openai "Gemini Local Test" :host "localhost:4100" :protocol "http"
                                          :key "x" :models '(gemini-gemma-free)))
        (gptel-model 'gemini-gemma-free)
        (sent nil) msg)
    (cl-letf (((symbol-function 'gptel-request) (lambda (&rest _) (setq sent t))))
      (setq msg (condition-case err (progn (kyo/proofread-region) nil) (user-error (error-message-string err))))
      (test-check "I1 proofread refuses with a plain message" (and msg (string-match-p "The gptel backend Gemini Local Test is not running: nothing answers at localhost:4100" msg)) msg)
      (test-check "I2 nothing was sent" (not sent))
      (let ((kyo/prose-gptel-backend "Test Remote") (kyo/prose-gptel-model 'm) seen)
        (cl-letf (((symbol-function 'gptel-request)
                   (lambda (&rest _) (setq seen (list (gptel-backend-name gptel-backend) gptel-model)))))
          (kyo/proofread-region))
        (test-check "I3 kyo/prose-gptel-backend and -model are used" (equal seen '("Test Remote" m)) (format "%S" seen))))))

;; K. the card stands apart: padding, a border in the underline's color, its own background
(set-face-attribute 'default nil :background "#0D0D0D" :foreground "#ebdbb2")
(set-face-attribute 'minibuffer-prompt nil :foreground "#8d8d8d")
(set-face-attribute 'flycheck-error nil :underline '(:style wave :color "#E46E6E"))
(set-face-attribute 'flycheck-info nil :underline '(:style wave :color "#74A8C7"))
(require 'jinx)
(set-face-attribute 'jinx-misspelled nil :underline '(:style wave :color "#d2b580"))
(let* ((grammar (list :level 'error :kind "Grammar" :message "A long message that the card fills across two lines because it goes on and on past seventy-two columns." :beg 1 :end 2
                      :fixes (list (list "Use this" 'replace "this"))))
       (spelling (list :level 'error :kind "Spelling" :message "S" :beg 1 :end 2 :fixes nil))
       (clarity (list :level 'info :kind "Clarity" :message "C" :beg 1 :end 2 :fixes nil))
       (card (with-temp-buffer (kyo/prose--card-text (list grammar)))))
  (test-check "K1 every card line has a space of padding on both sides"
              (seq-every-p (lambda (l) (and (string-prefix-p " " l) (string-suffix-p " " l))) (split-string card "\n"))
              (format "%S" (split-string (substring-no-properties card) "\n")))
  (test-check "K2 grammar border = Flycheck's error underline" (equal (kyo/prose--underline-color grammar) "#E46E6E"))
  (test-check "K3 spelling border = jinx's underline" (equal (kyo/prose--underline-color spelling) "#d2b580"))
  (test-check "K4 suggestion border = Flycheck's info underline" (equal (kyo/prose--underline-color clarity) "#74A8C7"))
  (test-check "K5 the kind is drawn in the underline's color"
              (equal (plist-get (get-text-property 1 'face card) :foreground) "#E46E6E")
              (format "%S" (get-text-property 1 'face card)))
  (let ((bg (kyo/prose--card-background)))
    (test-check "K6 the card's background is the buffer's" (equal bg (face-background 'default nil t)) bg))
  (let (args)
    (require 'posframe)
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
              ((symbol-function 'posframe-workable-p) (lambda (&rest _) t))
              ((symbol-function 'posframe-show) (lambda (_buffer &rest rest) (setq args rest))))
      (with-temp-buffer
        (insert "x")
        (kyo/prose--show-card (list grammar) 1 'cursor)))
    (test-check "K7 posframe gets a 2 px border" (eql (plist-get args :border-width) 2) (format "%S" (plist-get args :border-width)))
    (test-check "K8 in the theme's accent" (equal (plist-get args :border-color) "#8d8d8d") (plist-get args :border-color))
    (test-check "K9 on the card's own background" (equal (plist-get args :background-color) (kyo/prose--card-background)) (plist-get args :background-color))
    (setq kyo/prose--card nil)))

;; L. the model's suggestions, underlined and on the same card
(defvar test-messages nil)
(defun test-ai-buffer ()
  (let ((buf (get-buffer-create "*ai-test*")))
    (with-current-buffer buf
      (erase-buffer)
      (insert "#+TITLE: We was here\n\nWe was building the platform, and it work good.\nThe second line\nwraps here.\n")
      (org-mode))
    buf))
(defvar test-answer "Here you go:\n```json\n{\"suggestions\": [\n {\"original\": \"We was building\", \"replacement\": \"We were building\", \"category\": \"correctness\", \"title\": \"Fix the verb agreement\", \"explanation\": \"The plural subject takes were.\"},\n {\"original\": \"it work good\", \"replacement\": \"it worked well\", \"category\": \"clarity\", \"title\": \"Use the adverb\", \"explanation\": \"Good describes nouns; well describes verbs.\"},\n {\"original\": \"We was here\", \"replacement\": \"We were here\", \"category\": \"correctness\", \"title\": \"Fix the title\", \"explanation\": \"x\"},\n {\"original\": \"second line wraps\", \"replacement\": \"second line, wrapped\", \"category\": \"engagement\", \"title\": \"Join the line\", \"explanation\": \"y\"},\n {\"original\": \"not in the text\", \"replacement\": \"z\", \"category\": \"delivery\", \"title\": \"Gone\", \"explanation\": \"z\"}\n]}\n```\n")
(defun test-ai-info (buf label)
  (with-current-buffer buf
    (list :context (list :beg (copy-marker (point-min)) :end (copy-marker (point-max) t)
                         :label label :backend "xAI"))))
(defmacro test-capturing-messages (&rest body)
  `(progn (setq test-messages nil)
          (cl-letf (((symbol-function 'message)
                     (lambda (fmt &rest args) (push (and fmt (apply #'format-message fmt args)) test-messages))))
            ,@body)))
(set-face-attribute 'error nil :foreground "#E46E6E")
(set-face-attribute 'link nil :foreground "#74A8C7")
(set-face-attribute 'success nil :foreground "#86D993")
(set-face-attribute 'link-visited nil :foreground "#B7A1C7")
(test-check "L1 a fenced JSON answer parses" (= (length (kyo/prose--ai-parse test-answer)) 5))
(with-current-buffer (test-ai-buffer)
  (test-capturing-messages (kyo/prose--ai-response test-answer (test-ai-info (current-buffer) "AI proofread")))
  (let ((ovs (seq-filter (lambda (ov) (overlay-get ov 'kyo-ai)) (overlays-in (point-min) (point-max)))))
    (test-check "L2 three of five placed: the title line and missing text skipped" (= (length ovs) 3)
                (mapcar (lambda (ov) (buffer-substring-no-properties (overlay-start ov) (overlay-end ov))) ovs))
    (test-check "L3 the count is reported" (equal (car test-messages) "AI proofread: 3 of 5 suggestions underlined; the rest no longer match the text") (car test-messages))
    (test-check "L4 a span across a line break is found" (seq-some (lambda (ov) (equal (buffer-substring-no-properties (overlay-start ov) (overlay-end ov)) "second line\nwraps")) ovs)))
  (goto-char (point-min)) (search-forward "We was building") (backward-char 4)
  (let* ((ov (seq-find (lambda (o) (overlay-get o 'kyo-ai)) (overlays-at (point))))
         (issues (kyo/prose--issues-at (point)))
         (card (kyo/prose--card-text issues))
         (plain (substring-no-properties card)))
    (test-check "L5 the underline is Correctness red" (equal (plist-get (plist-get (overlay-get ov 'face) :underline) :color) "#E46E6E"))
    (test-check "L6 the card names the kind, headline and why"
                (and (string-match-p "Correctness  Fix the verb agreement" plain) (string-match-p "The plural subject takes were\\." plain)) plain)
    (test-check "L7 the change reads old then new, word by word" (string-match-p "We was were building" plain) plain)
    (let ((was (string-match "was were" card)))
      (test-check "L8 the old word is struck, the new one in the category color"
                  (and (plist-get (get-text-property was 'face card) :strike-through)
                       (equal (plist-get (get-text-property (+ was 4) 'face card) :foreground) "#E46E6E"))
                  (list (get-text-property was 'face card) (get-text-property (+ was 4) 'face card))))
    (test-check "L9 the fixes are 1 Accept, 2 Dismiss" (and (string-match-p "1  Accept" plain) (string-match-p "2  Dismiss" plain)))
    (setq unread-command-events (list ?1))
    (kyo/prose-fix-at-point)
    (test-check "L10 z=1 accepts the suggestion" (string-match-p "We were building the platform" (buffer-string)) (buffer-string))
    (test-check "L11 and the underline goes" (not (overlay-buffer ov))))
  (goto-char (point-min)) (search-forward "it work good") (backward-char 3)
  (let ((ov (seq-find (lambda (o) (overlay-get o 'kyo-ai)) (overlays-at (point)))))
    (setq unread-command-events (list ?2))
    (kyo/prose-fix-at-point)
    (test-check "L12 z=2 dismisses: the text stays, the underline goes"
                (and (string-match-p "it work good" (buffer-string)) (not (overlay-buffer ov)))))
  (goto-char (point-min)) (search-forward "second line") (backward-char 3)
  (let ((ov (seq-find (lambda (o) (overlay-get o 'kyo-ai)) (overlays-at (point)))))
    (insert "x")
    (test-check "L13 editing inside a suggestion drops it" (not (overlay-buffer ov)))))
(with-current-buffer (test-ai-buffer)
  (test-capturing-messages
   (kyo/prose--ai-response nil (append (list :status "HTTP/2 403" :error "Your team f29 has either used all available credits or reached its monthly spending limit.")
                                       (test-ai-info (current-buffer) "AI proofread"))))
  (test-check "L14 a refused request shows the provider's reason"
              (equal (car test-messages) "AI proofread failed: xAI (HTTP/2 403): Your team f29 has either used all available credits or reached its monthly spending limit.")
              (car test-messages))
  (test-capturing-messages (kyo/prose--ai-response "Sorry, I cannot help with that." (test-ai-info (current-buffer) "AI flow")))
  (test-check "L15 an answer with no JSON is reported" (equal (car test-messages) "AI flow: the answer was not the JSON asked for") (car test-messages))
  (let ((info (test-ai-info (current-buffer) "AI flow")))
    (test-capturing-messages (kyo/prose--ai-response '(reasoning . "thinking...") info))
    (test-check "L16 reasoning text is skipped, the request stays open"
                (and (null test-messages) (marker-buffer (plist-get (plist-get info :context) :beg))))))
(with-current-buffer (test-ai-buffer)
  (goto-char (point-min)) (search-forward "platform")
  (kyo/prose--ai-overlay (point) (+ (point) 2) (list :original "x" :replacement "y" :category "delivery"))
  (let ((gptel-backend (gptel-make-openai "Test Remote" :host "api.example.invalid" :key "x" :models '(m)))
        (gptel-model 'm)
        captured)
    (cl-letf (((symbol-function 'gptel-request) (lambda (prompt &rest args) (setq captured (cons prompt args)))))
      (test-capturing-messages (kyo/proofread-region)))
    (let ((system (plist-get (cdr captured) :system)))
      (test-check "L17 the prompt is the paragraph at point" (equal (car captured) "We was building the platform, and it work good.\nThe second line\nwraps here.") (car captured))
      (test-check "L18 the rules lose their \"Return only\" line and gain the JSON format"
                  (and (string-match-p "## Answer format" system) (not (string-match-p "^Return only" system))
                       (string-match-p "## What to fix" system)))
      (test-check "L19 no transforms, no stream, markers in the context"
                  (and (plist-member (cdr captured) :transforms) (null (plist-get (cdr captured) :transforms))
                       (null (plist-get (cdr captured) :stream))
                       (markerp (plist-get (plist-get (cdr captured) :context) :beg))))
      (test-check "L20 old suggestions in the paragraph are cleared first"
                  (null (seq-filter (lambda (ov) (overlay-get ov 'kyo-ai)) (overlays-in (point-min) (point-max))))))))
(let ((steps (kyo/prose--word-diff (kyo/prose--words "a big dog") (kyo/prose--words "a dog"))))
  (test-check "L21 the word diff keeps shared words and drops the rest"
              (equal steps '((same . "a") (same . " ") (del . "big") (del . " ") (same . "dog"))) (format "%S" steps)))

;; M. Claude through the Claude Code CLI, a fake one that records its call
(defvar test-fake (expand-file-name "fake-claude.sh" test-dir))
(defun test-read (name)
  "Read what the fake CLI recorded under NAME, in FAKE_CLAUDE_OUT or next to it."
  (with-temp-buffer
    (insert-file-contents (expand-file-name name (or (getenv "FAKE_CLAUDE_OUT") test-dir)))
    (buffer-string)))
(defun test-run-claude (mode timeout)
  "Run the proofread on the AI test buffer with the fake CLI in MODE."
  (with-current-buffer (test-ai-buffer)
    (goto-char (point-min)) (search-forward "platform")
    (let ((kyo/prose-ai-engine 'claude)
          (kyo/prose-claude-program test-fake)
          (kyo/prose-claude-timeout timeout)
          (process-environment (append (list "CLAUDE_CONFIG_DIR=/home/kyonax/.claude-work"
                                             (concat "FAKE_CLAUDE_MODE=" mode))
                                       process-environment)))
      (test-capturing-messages
       (let ((proc (kyo/proofread-region))
             (deadline (+ (float-time) 10)))
         (while (and (process-live-p proc) (< (float-time) deadline))
           (accept-process-output proc 0.1))
         (accept-process-output nil 0.2))))
    (current-buffer)))
(let* ((buf (test-run-claude "ok" 30))
       (args (split-string (test-read "fake-claude.args") "\n")))
  (test-check "M1 the CLI gets -p, Sonnet at medium effort, JSON with the schema"
              (and (member "-p" args) (equal (cadr (member "--model" args)) "sonnet")
                   (equal (cadr (member "--effort" args)) "medium")
                   (equal (cadr (member "--output-format" args)) "json")
                   (string-match-p "\"suggestions\"" (cadr (member "--json-schema" args))))
              (format "%S" (seq-take args 8)))
  (test-check "M2 no tools, no settings, no MCP servers, no saved session"
              (and (equal (cadr (member "--tools" args)) "") (equal (cadr (member "--setting-sources" args)) "")
                   (member "--strict-mcp-config" args) (member "--no-session-persistence" args)))
  (let ((system (test-read "fake-claude.args")))
    (test-check "M3 the system prompt is the rules plus the JSON format, without \"Return only\""
                (and (string-match-p "## What to fix" system) (string-match-p "## Answer format" system)
                     (not (string-match-p "^Return only" system)))))
  (test-check "M4 the text goes in on stdin" (equal (test-read "fake-claude.stdin") "We was building the platform, and it work good.\nThe second line\nwraps here.")
              (test-read "fake-claude.stdin"))
  (test-check "M5 it runs from the temp directory" (equal (string-trim (test-read "fake-claude.cwd")) (directory-file-name temporary-file-directory)))
  (test-check "M6 the personal account: CLAUDE_CONFIG_DIR is dropped" (equal (string-trim (test-read "fake-claude.env")) "0"))
  (test-check "M7 Claude's structured answer is underlined" (equal (car test-messages) "AI proofread: 2 suggestions underlined") (car test-messages))
  (with-current-buffer buf
    (test-check "M8 two underlines" (= 2 (length (seq-filter (lambda (ov) (overlay-get ov 'kyo-ai)) (overlays-in (point-min) (point-max))))))))
(test-run-claude "error" 30)
(test-check "M9 an error from the CLI is shown in its own words"
            (equal (car test-messages) "AI proofread failed: Claude (exit 1): Not logged in · Please run /login") (car test-messages))
(test-run-claude "slow" 1)
(test-check "M10 a CLI that hangs is stopped at the timeout"
            (equal (car test-messages) "AI proofread failed: Claude did not answer within 1 s") (car test-messages))

;; M11. the answer is used the moment it is complete, not when the CLI exits
(with-current-buffer (test-ai-buffer)
  (goto-char (point-min)) (search-forward "platform")
  (let ((kyo/prose-ai-engine 'claude)
        (kyo/prose-claude-program test-fake)
        (kyo/prose-claude-timeout 30)
        (process-environment (cons "FAKE_CLAUDE_MODE=linger" process-environment))
        live-at-answer)
    (test-capturing-messages
     (let ((proc (kyo/proofread-region))
           (deadline (+ (float-time) 10)))
       (while (and (< (float-time) deadline)
                   (not (seq-some (lambda (m) (and m (string-match-p "underlined" m))) test-messages)))
         (accept-process-output proc 0.05))
       (setq live-at-answer (process-live-p proc))
       (while (and (process-live-p proc) (< (float-time) deadline))
         (accept-process-output proc 0.1))
       (accept-process-output nil 0.2)))
    (test-check "M11 suggestions land while the CLI still lingers" live-at-answer)
    (test-check "M12 and are reported once"
                (= 1 (length (seq-filter (lambda (m) (and m (string-match-p "underlined\\|failed" m))) test-messages)))
                (format "%S" test-messages))))

;; N. the selection's card
(with-current-buffer (test-ai-buffer)
  (transient-mark-mode 1)
  (setq-local kyo-prose-mode t)
  (setq kyo/prose--card nil)
  (goto-char (point-min)) (search-forward "\n\nWe")
  (let ((start (- (point) 2)))
    (set-mark start) (goto-char (+ start 6)) (activate-mark)
    (test-check "N1 two words are not enough for a selection card" (not (kyo/prose--selection-p)))
    (goto-char (+ start 19))
    (test-check "N2 four words are" (kyo/prose--selection-p))
    (let ((card (substring-no-properties (kyo/prose--card-text (list (kyo/prose--selection-issue))))))
      (test-check "N3 the card offers the model's two checks on it"
                  (and (string-match-p "Selection  4 words selected" card) (string-match-p "1  Proofread it" card)
                       (string-match-p "2  Improve the flow" card))
                  card))
    (let (shown)
      (cl-letf (((symbol-function 'kyo/prose--show-card)
                 (lambda (issues _pos trigger) (setq shown (list trigger (plist-get (car issues) :kind))))))
        (kyo/prose--card-at-point)
        (test-check "N4 the cursor card stays quiet while a selection is up" (null shown) (format "%S" shown))
        (kyo/prose--card-at-selection)
        (test-check "N5 the selection's card opens" (equal shown '(selection "Selection")) (format "%S" shown))))
    (let (called)
      (cl-letf (((symbol-function 'kyo/prose--ai-check) (lambda (&rest args) (setq called args))))
        (setq unread-command-events (list ?1))
        (kyo/prose-fix-at-point)
        (test-check "N6 z=1 on a selection proofreads exactly that text"
                    (and (equal (nth 1 called) "AI proofread") (eql (nth 2 called) start) (eql (nth 3 called) (+ start 19))
                         (string-match-p "proofread\\.md\\'" (nth 0 called)))
                    (format "%S" called))))
    (setq kyo/prose--card (list (current-buffer) (point) (buffer-chars-modified-tick) 'selection (point)
                                (list (kyo/prose--selection-issue))))
    (test-check "N7 the card on screen is what z= reads" (equal (plist-get (car (kyo/prose--card-issues)) :kind) "Selection"))
    (let (called)
      (cl-letf (((symbol-function 'kyo/prose--ai-check) (lambda (&rest args) (setq called args))))
        (setq unread-command-events (list ?2))
        (kyo/prose-fix-at-point)
        (test-check "N8 z=2 on the selection's card runs the flow check on it"
                    (and (equal (nth 1 called) "AI flow") (eql (nth 2 called) start)) (format "%S" called))))
    (setq kyo/prose--card (list (current-buffer) (point) (buffer-chars-modified-tick) 'selection (point)
                                (list (kyo/prose--selection-issue))))
    (deactivate-mark)
    (test-check "N9 the selection's card goes with the selection" (kyo/prose--card-hidehandler nil))
    (setq kyo/prose--card nil)))
(let (called)
  (cl-letf (((symbol-function 'kyo/prose--ai-check) (lambda (&rest args) (setq called args))))
    (kyo/prose--apply (list :op 'ai :arg (cons "rules.md" "AI flow") :beg 5 :end 20))
    (test-check "N10 a click on a selection fix runs that check on that span" (equal called '("rules.md" "AI flow" 5 20)) (format "%S" called))))

;; O. Ask: an instruction of my own
(with-current-buffer (test-ai-buffer)
  (goto-char (point-min)) (search-forward "platform")
  (let ((kyo/prose-ai-engine 'claude)
        (kyo/prose-claude-program test-fake)
        (kyo/prose-claude-timeout 30)
        (process-environment (cons "FAKE_CLAUDE_MODE=ok" process-environment)))
    (test-capturing-messages
     (let ((proc (kyo/prose-ask "use fewer ands"))
           (deadline (+ (float-time) 10)))
       (while (and (process-live-p proc) (< (float-time) deadline))
         (accept-process-output proc 0.1))
       (accept-process-output nil 0.2)))
    (let ((system (test-read "fake-claude.args")))
      (test-check "O1 the instruction is the point of the check, under the rules and the format"
                  (and (string-match-p "## The author's request\nuse fewer ands\n" system)
                       (string-match-p "## What to fix" system) (string-match-p "## Answer format" system))))
    (test-check "O2 its suggestions are underlined like the others"
                (equal (car test-messages) "AI ask: 2 suggestions underlined") (car test-messages))))
(cl-letf (((symbol-function 'read-string) (lambda (&rest _) "   ")))
  (test-check "O3 an empty instruction is refused"
              (condition-case err (progn (kyo/prose--read-request) nil)
                (user-error (equal (error-message-string err) "No instruction given")))))
(with-current-buffer (test-ai-buffer)
  (transient-mark-mode 1)
  (goto-char (point-min)) (search-forward "\n\nWe")
  (let ((start (- (point) 2)) called)
    (set-mark start) (goto-char (+ start 19)) (activate-mark)
    (test-check "O4 the selection's card offers Ask third"
                (string-match-p "3  Ask about it\\.\\.\\."
                                (substring-no-properties (kyo/prose--card-text (list (kyo/prose--selection-issue))))))
    (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "bold the key words"))
              ((symbol-function 'kyo/prose--ai-check) (lambda (&rest args) (setq called args))))
      (setq unread-command-events (list ?3))
      (kyo/prose-fix-at-point))
    (test-check "O5 z=3 asks about exactly the selection"
                (and (equal (nth 1 called) "AI ask") (eql (nth 2 called) start) (eql (nth 3 called) (+ start 19))
                     (equal (nth 4 called) "bold the key words"))
                (format "%S" called))
    (deactivate-mark)))

;; P. a check's suggestions all at once, and walking the underlines
(with-current-buffer (test-ai-buffer)
  (let ((info (test-ai-info (current-buffer) "AI proofread")))
    (plist-put (plist-get info :context) :id 41)
    (test-capturing-messages (kyo/prose--ai-response test-answer info)))
  (goto-char (point-min)) (search-forward "it work good") (backward-char 3)
  (let ((plain (substring-no-properties (kyo/prose--card-text (kyo/prose--issues-at (point))))))
    (test-check "P1 the card offers all of its check's suggestions"
                (and (string-match-p "3  Accept all 3" plain) (string-match-p "4  Dismiss all 3" plain)) plain)
    (test-check "P2 and the keys to walk the underlines" (string-match-p "]s next underline, \\[s previous" plain)))
  (setq unread-command-events (list ?3))
  (test-capturing-messages (kyo/prose-fix-at-point))
  (test-check "P3 z=3 accepts all three"
              (and (string-match-p "We were building the platform, and it worked well\\." (buffer-string))
                   (string-match-p "second line, wrapped" (buffer-string))
                   (null (kyo/prose--ai-overlays)))
              (buffer-string))
  (test-check "P4 and says so" (equal (car test-messages) "Accepted 3 suggestions") (car test-messages)))
(with-current-buffer (test-ai-buffer)
  (let ((info (test-ai-info (current-buffer) "AI proofread")))
    (plist-put (plist-get info :context) :id 42)
    (test-capturing-messages
     (kyo/prose--ai-response "{\"suggestions\": [{\"original\": \"it work good\", \"replacement\": \"it worked well\", \"category\": \"clarity\", \"title\": \"t\", \"explanation\": \"e\"}]}" info)))
  (goto-char (point-min)) (search-forward "it work good") (backward-char 3)
  (let ((plain (substring-no-properties (kyo/prose--card-text (kyo/prose--issues-at (point))))))
    (test-check "P5 a lone suggestion offers no \"all\"" (not (string-match-p "Accept all" plain)) plain)))
(with-current-buffer (test-ai-buffer)
  (let ((info (test-ai-info (current-buffer) "AI proofread")))
    (plist-put (plist-get info :context) :id 43)
    (test-capturing-messages (kyo/prose--ai-response test-answer info)))
  (let ((before (buffer-string)))
    (goto-char (point-min)) (search-forward "it work good") (backward-char 3)
    (setq unread-command-events (list ?4))
    (test-capturing-messages (kyo/prose-fix-at-point))
    (test-check "P6 z=4 dismisses all three and leaves the text alone"
                (and (equal before (buffer-string)) (null (kyo/prose--ai-overlays))) (car test-messages))))
(with-current-buffer (get-buffer-create "*ai-test-2*")
  (erase-buffer)
  (insert "We was here first.\n\nWe was here second.\n")
  (org-mode)
  (let ((info (list :context (list :beg (copy-marker (point-min)) :end (copy-marker (point-max) t)
                                   :label "AI proofread" :backend "x" :id 44))))
    (test-capturing-messages
     (kyo/prose--ai-response "{\"suggestions\": [{\"original\": \"We was here first\", \"replacement\": \"We were here first\", \"category\": \"correctness\", \"title\": \"t\", \"explanation\": \"e\"}, {\"original\": \"We was here second\", \"replacement\": \"We were here second\", \"category\": \"correctness\", \"title\": \"t\", \"explanation\": \"e\"}]}" info)))
  (goto-char (point-min)) (search-forward "first")
  (test-capturing-messages (kyo/prose-ai-accept-all))
  (test-check "P7 SPC o l A accepts the paragraph's suggestions only"
              (and (string-match-p "We were here first" (buffer-string)) (string-match-p "We was here second" (buffer-string))
                   (= 1 (length (kyo/prose--ai-overlays))))
              (buffer-string))
  (test-capturing-messages (kyo/prose-ai-accept-all t))
  (test-check "P8 with a prefix, the whole buffer's"
              (and (string-match-p "We were here second" (buffer-string)) (null (kyo/prose--ai-overlays)))
              (buffer-string)))
(with-current-buffer (get-buffer-create "*ai-test-3*")
  (erase-buffer)
  (insert "One two three four five six seven eight nine ten.\n")
  (org-mode)
  (let ((a (make-overlay 5 8)) (b (make-overlay 15 20)) (c (make-overlay 25 30)))
    (overlay-put a 'kyo-ai '(:replacement "x"))
    (overlay-put b 'flycheck-overlay t)
    (overlay-put c 'category 'jinx-overlay)
    (goto-char 1)
    (kyo/prose-next-issue)
    (test-check "P9 ]s goes to the next underline" (= (point) 5) (point))
    (kyo/prose-next-issue 2)
    (test-check "P10 a count skips ahead, through every kind of underline" (= (point) 25) (point))
    (kyo/prose-previous-issue)
    (test-check "P11 [s goes back" (= (point) 15) (point))
    (goto-char 26)
    (test-capturing-messages (kyo/prose-next-issue))
    (test-check "P12 past the last one it says so and stays"
                (and (= (point) 26) (equal (car test-messages) "No more underlines after this one")) (car test-messages))))

(princ (format "\n%s: %d failure(s)\n" (if (zerop test-failures) "ALL PASS" "FAILURES") test-failures))
(kill-emacs (if (zerop test-failures) 0 1))
