#+TITLE: THE DOOM CONFIG
#+SUBTITLE: All my Doom Emacs Configuration Files
#+AUTHOR: Cristian D. Moreno - Kyonax
#+EMAIL: kyonax.corp@gmail.com
#+DATE: June 20, 2025
#+LAST_UPDATE: November 07, 2025
#+PROJECT: dot-files
#+VERSION: v1.0
#+KEYWORDS: emacs, docs, doom config
#+auto_tangle: t

This ain't an average *doom-config file*, this is the master index of my entire Doom Emacs setup. Just one file, locked on generating the necessary tweaks to maintain my setup across all OS. My master file, jacked to fit my pesonal needs. Use it as your blueprint, but don't even think about PRs.

* MAINTABLE OF CONTENTs :toc:
- [[#main][MAIN]]
  - [[#os-prober][OS PROBER]]
  - [[#user--host][USER & HOST]]
  - [[#environment-profile][ENVIRONMENT PROFILE]]
  - [[#identity][IDENTITY]]
- [[#config-files][CONFIG FILEs]]
  - [[#packagesel][packages.el]]
  - [[#configel][config.el]]
  - [[#initel][init.el]]
- [[#custom-functions][CUSTOM FUNCTIONs]]
  - [[#create-invoice-number][CREATE INVOICE NUMBER]]

* MAIN
This file's wired into ~org-mode~ and ~org-babel~, to follow the idea of Literate Programming (in my case for configuration files), that's why is necessary a section to configure all the necessary stuff to make the Master File do magick.

** OS PROBER
One-File for All-OS, my main directive was to create a single file to tangle everything, no matter the OS I'm into. This OS PROBER section is locked on deploying ~org-babel~ and nailing down which blocks get tangled, all hinging on the data pulled from the =get-os-variable= block.

Call the function in a condition when creating the ~:tangle~ property in blocks, to identify if the block will be tangled depending on the OS.

#+NAME: get-os-type
#+begin_src emacs-lisp :tangle no :exports results :results value
(cond ((eq system-type 'gnu/linux)   "linux")
      ((eq system-type 'darwin)      "mac")
      ((eq system-type 'windows-nt)  "windows")
      ((eq system-type 'cygwin)      "cygwin")
      (t "unknown"))
#+end_src

Example of Usage:
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(message "Hello There I'm on %s" (org-babel-ref-resolve "get-os-type"))
#+end_src

** USER & HOST
*Multi-OS, One Setup* — I keep a unified configuration across all my systems, but each OS comes with its own users, hosts, and unique context. Depending on whether I’m using Emacs for work, personal projects, or any other scenario, certain configurations adapt dynamically. This setup helps me instantly recognize where I am and ensures the right configuration loads for the right environment.

#+NAME: get-username
#+begin_src emacs-lisp :tangle no :exports results :results value
(let ((os (org-babel-ref-resolve "get-os-type")))
  (cond
   ((string= os "linux")   (user-login-name))
   ((string= os "mac")     (user-login-name))
   ((string= os "windows") (getenv "USERNAME"))
   ((string= os "cygwin")  (getenv "USERNAME"))
   (t "unknown-user")))
#+end_src

#+NAME: get-hostname
#+begin_src emacs-lisp :tangle no :exports results :results value
(let ((os (org-babel-ref-resolve "get-os-type")))
  (cond
   ((member os '("linux" "mac"))
    (string-trim (shell-command-to-string "hostname")))
   ((member os '("windows" "cygwin"))
    (or (getenv "COMPUTERNAME") "unknown-host"))
   (t "unknown-host")))
#+end_src

Example of Usage:
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(message "This is my Username %s" (org-babel-ref-resolve "get-username"))
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(message "This is my Hostname %s" (org-babel-ref-resolve "get-hostname"))
#+end_src

** ENVIRONMENT PROFILE
*Profile Selector* — This is where I choose the active profile to ensure each environment loads the right configuration for the context I’m in.

#+NAME: get-profile
#+begin_src emacs-lisp :tangle no :exports results :results value
(let* ((hostname (downcase (org-babel-ref-resolve "get-hostname"))))
  (cond
   ((string-match-p "kyo-labs" hostname) "personal-linux")
   ((string-match-p "MacBook-Pro-de-COL-AE-052.local" hostname) "work-mac")
   (t "default")))
#+end_src

Example of Usage:
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(message "This is my Profile %s" (org-babel-ref-resolve "get-profile"))
#+end_src

** IDENTITY
*Who Am I?* — Depending on the active profile, I can be anyone. My identity, along with settings for tools, templates, and other resources, updates automatically to match that context.

#+NAME: get-name
#+begin_src emacs-lisp :tangle no :exports results :results value
(let* ((profile (org-babel-ref-resolve "get-profile")))
  (cond
   ((string= profile "personal-linux")
    "Cristian D. Moreno - Kyonax")
   ((string= profile "work-mac")
    "Cristian D. Moreno - Agile Engine")
   (t "Cristian D. Moreno")))
#+end_src

#+NAME: get-email
#+begin_src emacs-lisp :tangle no :exports results :results value
(let* ((profile (org-babel-ref-resolve "get-profile")))
  (cond
   ((string= profile "personal-linux")
    "kyonax.corp@gmail.com")
   ((string= profile "work-mac")
    "cristian.moreno@agileengine.com")
   (t "kyonax.corp@gmail.com")))
#+end_src

*Example of Usage:*
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(message "This is my Profile %s" (org-babel-ref-resolve "get-name"))
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(message "This is my Profile %s" (org-babel-ref-resolve "get-email"))
#+end_src

* CONFIG FILEs
** packages.el
Doom comes with the Default package manager for Doom Emacs, where all the packages will be installed when the command ~doom sync~ is run by the user.

*** DEFAULT FILE DOCUMENTATION
#+begin_src emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;; (package! another-package
;;   :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;; (package! this-package
;;   :recipe (:host github :repo "username/repo"
;;            :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;; (package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;; (package! builtin-package :recipe (:nonrecursive t))
;; (package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;; (package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;; (package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;; (unpin! pinned-package)
;; ...or multiple packages
;; (unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;; (unpin! t)
#+end_src

*** BEACON
#+begin_src emacs-lisp :tangle packages.el
(package! beacon)
#+end_src
*** BIBLIO
#+begin_src emacs-lisp :tangle packages.el
(package! bibtex-completion)
(package! parsebib)
(package! ivy-bibtex)
#+end_src
*** CALENDAR
#+begin_src emacs-lisp :tangle packages.el
(package! calfw)
(package! calfw-org)
(package! org-gcal)
#+end_src

*** CAPE
#+begin_src emacs-lisp :tangle packages.el
(package! cape)
#+end_src

*** CLIPPY
#+begin_src emacs-lisp :tangle packages.el
(package! clippy)
#+end_src

*** CORFU
#+begin_src emacs-lisp :tangle packages.el
(package! corfu)
(package! nerd-icons-corfu)
(package! orderless)
(package! corfu-terminal)
#+end_src
*** DEFAULT
#+begin_src emacs-lisp :tangle packages.el
(package! drag-stuff)
#+end_src

*** DIRED-OPEN
#+begin_src emacs-lisp :tangle packages.el
(package! dired-open)
#+end_src

*** DIRED-SUBTREE
#+begin_src emacs-lisp :tangle packages.el
(package! dired-subtree)
#+end_src

*** EDITORCONFIG
#+begin_src emacs-lisp :tangle packages.el
(package! editorconfig)
#+end_src

*** ELFEEDED-GOODIES
#+begin_src emacs-lisp :tangle packages.el
(package! elfeed-goodies)
#+end_src

*** EMOJIFY
#+begin_src emacs-lisp :tangle packages.el
(package! emojify)
#+end_src

*** EVIL
#+begin_src emacs-lisp :tangle packages.el
(package! evil-tutor)
(package! evil-nerd-commenter)
#+end_src

*** FLX
#+begin_src emacs-lisp :tangle packages.el
(package! flx)
#+end_src

*** FOLD
#+begin_src emacs-lisp :tangle packages.el
(package! treesit-fold)
#+end_src

*** GPTEL
#+begin_src emacs-lisp :tangle packages.el
(package! gptel)
(package! gptel-quick)
(package! gptel-magit)
#+end_src

*** IVY
#+begin_src emacs-lisp :tangle packages.el
(package! ivy-hydra)
(package! ivy-posframe)
(package! ivy-prescient)
(package! nerd-icons-ivy-rich)
#+end_src

*** LANG
#+begin_src emacs-lisp :tangle packages.el
(package! opencl-mode)
(package! ccls)

(package! flycheck-cask)

(package! cdlatex)

(package! grip-mode)
(package! markdown-ts-mode)

(package! org-fancy-priorities)
(package! org-superstar)
(package! org-contacts)
(package! org-download)
(package! gnuplot)
(package! gnuplot-mode)
(package! ox-hugo)
(package! jupyter)
(package! org-noter)
(package! ox-pandoc)
(package! org-passwords)
(package! org-pomodoro)
(package! centered-window)
(package! org-tree-slide)
(package! org-re-reveal)
(package! org-appear)
(package! org-modern)
(package! org-roam)

(package! restclient-jq)
(package! jq-mode)

(package! swift-ts-mode)
(package! lsp-sourcekit)

(package! counsel-css)
(package! emmet-mode)
(package! haml-mode)
(package! pug-mode)
(package! rainbow-mode)
(package! sass-mode)
(package! slim-mode)
(package! stylus-mode)
(package! sws-mode)
(package! web-mode)
(package! yaml-mode)
#+end_src

*** LOOKUP
#+begin_src emacs-lisp :tangle packages.el
(when (modulep! :tools lookup +docsets)
  (package! dash-docs)
  (package! counsel-dash))
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "mac") "packages.el" "no")
(package! osx-dictionary)
#+end_src

*** LSP
#+begin_src emacs-lisp :tangle packages.el
(package! lsp-mode)
(package! lsp-ui)
(package! lsp-ivy)
#+end_src

*** MAGIT
#+begin_src emacs-lisp :tangle packages.el
(package! evil-magit)
(package! forge)
(package! code-review)
#+end_src

*** MACOS
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "mac") "packages.el" "no")
(package! osx-trash)
#+end_src

*** MULTIPLE-CURSORS
#+begin_src emacs-lisp :tangle packages.el
(package! multiple-cursors)
#+end_src

*** OLIVETTI
#+begin_src emacs-lisp :tangle packages.el
(package! olivetti)
#+end_src

*** ORDERLESS
#+begin_src emacs-lisp :tangle packages.el
(package! orderless)
#+end_src

*** ORG-AUTO-TANGLE
#+begin_src emacs-lisp :tangle packages.el
(package! org-auto-tangle)
#+end_src

*** ORG-BULLETS
#+begin_src emacs-lisp :tangle packages.el
(package! org-bullets)
#+end_src

*** ORG-WEB-TOOLS
#+begin_src emacs-lisp :tangle packages.el
(package! org-web-tools)
#+end_src

*** PASSWORD-STORE
#+begin_src emacs-lisp :tangle packages.el
(package! password-store)
#+end_src

*** PEEP-DIRED
#+begin_src emacs-lisp :tangle packages.el
(package! peep-dired)
#+end_src

*** RAINBOW-MODE
#+begin_src emacs-lisp :tangle packages.el
(package! rainbow-mode)
#+end_src

*** RESIZE-WINDOW
#+begin_src emacs-lisp :tangle packages.el
(package! resize-window)
#+end_src
*** SYNTAX
#+begin_src emacs-lisp :tangle packages.el
(package! flycheck-posframe)
#+end_src

*** TLDR
#+begin_src emacs-lisp :tangle packages.el
(package! tldr)
#+end_src

*** TREEMACS
#+begin_src emacs-lisp :tangle packages.el
(package! lsp-treemacs)
#+end_src

*** WC-MODE
#+begin_src emacs-lisp :tangle packages.el
(package! wc-mode)
#+end_src

*** WEB-MODE
#+begin_src emacs-lisp :tangle packages.el
(package! web-mode)
#+end_src
*** WINDOW-SELECT
#+begin_src emacs-lisp :tangle packages.el
(package! winum)
#+end_src

*** WORD-WRAP
#+begin_src emacs-lisp :tangle packages.el
(package! visual-fill-column)
#+end_src

*** ORG-ROAM-UI
#+begin_src emacs-lisp :tangle packages.el
(unpin! org-roam company-org-roam)
(package! org-roam-ui)
#+end_src

*** YASNIPPETS
#+begin_src emacs-lisp :tangle packages.el
(package! yasnippet-capf)
#+end_src

** config.el
*** EDITOR DEFAULTs
**** BEACON PACKAGE
Setup the ~beacon~ package to never lose the cursor. Shiny cursor interaction when moving.
#+begin_src emacs-lisp :tangle config.el
(use-package beacon
  :config
  (beacon-mode 1))

(setq evil-escape-key-sequence "jk")
#+end_src

**** BOOKMARKs
Setup the ~bookmarks~ for the editor.

- *Keybindings Bookmarks*
| COMMAND         | DESCRIPTION                            | KEYBINDING |
|-----------------+----------------------------------------+------------|
| list-bookmarks  | /List bookmarks/                         | SPC b L    |
| bookmark-set    | /Set bookmark/                           | SPC b m    |
| bookmark-delete | /Delete bookmark/                        | SPC b M    |
| bookmark-save   | /Save current bookmark to bookmark file/ | SPC b w    |

#+begin_src emacs-lisp :tangle config.el
(setq bookmark-default-file "~/.brain.d/bookmarks/bookmarks")

(map! :leader
      (:prefix ("b". "buffer")
       :desc "List bookmarks"                          "L" #'list-bookmarks
       :desc "Set bookmark"                            "m" #'bookmark-set
       :desc "Delete bookmark"                         "M" #'bookmark-set
       :desc "Save current bookmarks to bookmark file" "w" #'bookmark-save))
#+end_src

**** EDITORCONFIG PACKAGE
Enable the usage of ~editorconfig~ package. Consistency while develop [[https://github.com/editorconfig/editorconfig-emacs#readme][Read More]].
#+begin_src emacs-lisp :tangle config.el
(setq +file-templates-dir (expand-file-name "templates" doom-user-dir))

(use-package editorconfig
  :ensure t
  :hook (after-init . editorconfig-mode)
  :config
  (setq editorconfig-exclude-modes '(archive-mode
                                     image-mode
                                     pdf-view-mode))
  (setq editorconfig-trim-whitespaces-mode 'ws-butler-mode)

  ;; Espera a que cargue el major-mode antes de aplicar settings
  (setq editorconfig-lazy-major-mode t)
  (setq editorconfig-verbose nil))
#+end_src

**** FILE CODING SYSTEM
Set the File Coding System always to unix, this configuration is tweaked to maintain consistency across OS, used just on ~windows~ setup.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(set-buffer-file-coding-system 'utf-8-unix)
#+end_src

*Checker:*
#+begin_src emacs-lisp :tangle no
(message "%s" buffer-file-coding-system)
#+end_src

**** FONTs
Set the default fonts used across Emacs. There is just one font used right now in my Config:
- *Space Mono Nerd Font* [[https://www.nerdfonts.com/font-downloads][Nerd Fonts Website]].
#+begin_src emacs-lisp :tangle config.el
(setq doom-font (font-spec :family "SpaceMono Nerd Font Mono" :size 11)
      doom-variable-pitch-font (font-spec :family "SpaceMono Nerd Font Mono" :size 11)
      doom-big-font (font-spec :family "SpaceMono Nerd Font Mono" :size 18))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

**** GIT-SSH ASKPASS
Setup the =gui askpass=, to fill the passphrase with a GUI interface.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(setenv "SSH_ASKPASS" "C:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass")

(setenv "SSH_AUTH_SOCK" "\\\\.\\pipe\\openssh-ssh-agent")
#+end_src

**** TRUNCATE LINEs
Set a toggle keymap for ~truncated lines~, this is a toggle function.
#+begin_src emacs-lisp :tangle config.el
(map! :leader
      :desc "Toggle truncate lines"
      "t t" #'toggle-truncate-lines)
#+end_src

**** MELPA
Configure Melpa and enable the ~MELPA Stable~ packages repo. Comment the Stable configuration if not necessary the Stable version.
#+begin_src emacs-lisp :tangle config.el
(use-package package
  :config
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
  (package-initialize))
#+end_src

**** MODELINE PACKAGE
Setup the ~modeline~ package, this is the bottom status bar that appears in Emacs Windows. The Configuration is based on personal preferences to more information [[https://github.com/seagle0128/doom-modeline][Read More]].
#+begin_src emacs-lisp :tangle config.el
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  :init
  (setq doom-modeline-height 33
        doom-modeline-bar-width 6
        doom-modeline-icon t
        doom-modeline-major-mode-icon t
        doom-modeline-major-mode-color-icon t
        doom-modeline-buffer-file-name-style 'relative-to-project
        doom-modeline-minor-modes nil
        doom-modeline-enable-word-count nil
        doom-modeline-buffer-encoding t
        doom-modeline-indent-info t
        doom-modeline-vcs-max-length 15
        doom-modeline-persp-name t
        doom-modeline-persp-icon t
        doom-modeline-lsp t
        doom-modeline-github t
        doom-modeline-github-interval (* 15 60)
        doom-modeline-env-version t
        doom-modeline-mu4e nil
        doom-modeline-irc nil)
  :config
  (when (display-graphic-p)
    (set-face-attribute 'mode-line nil :font "SpaceMono Nerd Font Mono"))
  (doom-modeline-mode 1))
#+end_src

**** SERVER SOCKET
Generate the ~server-socket~ on a specific location. Daemon performance requirements.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(use-package server
  :config
  (setq server-use-tcp t
      server-socket-dir "~/.config/emacs/server"))
#+end_src

**** SHELL FOR COMPILATION
Setup the default ~shell~ to use for compilation. Create a toggle function for Windows to use Cygwin.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(defun kyo/toggle-shell-cygwin ()
  "Toggle between PowerShell and Cygwin as the default shell."
  (interactive)
  (if (string= shell-file-name "~/scoop/apps/pwsh/7.5.0/pwsh.exe")
      (setq shell-file-name "C:/cygwin/bin/bash.exe")
    (setq shell-file-name "~/scoop/apps/pwsh/7.5.0/pwsh.exe"))
  (message "Shell toggled to: %s" shell-file-name))

(setq shell-file-name "~/scoop/apps/pwsh/7.5.0/pwsh.exe")

(map! :leader
      :desc "Toggle Shells between PowerShell and Cygwin."
      "t h" #'kyo/toggle-shell-cygwin)
#+end_src

**** STARTUP WINDOW
Setup the ~doom-dashboard~ window to a customized one.
#+begin_src emacs-lisp :tangle no
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-shortmenu)

(add-hook! '+doom-dashboard-functions :append
  (insert "\n" (+doom-dashboard--center +doom-dashboard--width "I am Kyo")))

(defun kyo/my-shit-is-always-greater ()
  (let* ((banner '(
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣧⡀⣿⣤⣀⣾⣅⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣤⣤⠲⠶⣦⡿⣿⣿⣿⣿⣿⣿⣿⣴⣴⠖⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⢲⣦⣿⣟⠛⡓⣀⠐⠋⢽⠟⡿⢿⣿⣿⢛⢷⣤⣤⠄⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠠⢤⣦⣤⡦⠆⢈⢋⣡⡔⠁⢀⡠⠐⢻⡿⢃⡄⠀⣿⣧⣤⣀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⣀⣴⣾⡿⠗⡪⢛⣿⣿⣷⢾⡟⠀⣊⣴⣷⣿⢧⣦⣿⣿⢿⣁⣀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⢈⡬⠟⠂⠀⠖⠀⠞⠉⡽⠃⢈⠡⢋⠏⡰⠀⡿⠈⠛⣿⡇⠸⢢⡀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠊⠄⠁⠀⠐⣀⣪⢀⣔⡤⠂⣠⢀⡴⠀⣡⡀⠁⠈⠃⡢⠡⣄⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠄⠀⢤⣜⣉⡛⠻⢿⣷⣿⣿⣾⣷⡾⠿⠷⠆⢁⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⣾⠧⣬⣍⣑⠢⣽⣿⣿⣋⡤⠴⠒⢛⣳⣧⠀⠈⠀⢤⡄⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⣤⣧⠀⡄⢿⣧⡙⠛⠻⣤⣿⣿⣿⣿⣠⣿⡿⠟⣹⡧⠐⠠⠠⣿⡧⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⣠⣾⣿⣿⣧⡀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣾⡿⠁⢋⡄⠐⣿⣿⠀⠀⠀⠀"
                   "⠀⠀⢀⣼⣿⣿⣿⣿⣟⠀⠀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⣿⡧⠀⣿⣿⡀⣧⠀⠀"
                   "⠀⠀⣿⣿⣿⣿⣿⠛⢿⣷⡄⢢⠘⢿⣿⣿⣿⣿⣿⣿⣿⣿⠟⢁⠀⠀⢛⣩⣴⣿⡿⢃⡌⠀⠀"
                   "⠀⠀⠙⣿⣿⣿⣿⣿⣶⣌⠻⢦⡁⠀⠻⣿⣿⣿⣿⠿⠋⠀⣘⣡⣶⣿⡿⠟⣛⣡⠶⢋⠄⠀⠀"
                   "⠀⠀⠀⠈⠻⠿⡿⡿⣿⣿⣿⣦⣙⠢⠀⠀⠈⠈⣀⣤⣶⣿⣟⢛⡩⠔⣒⣩⣥⣤⣶⣿⠂⠀⠀"
                   "⠀⠀⠀⠀⠀⠰⣶⣦⣦⣦⡙⢿⡿⠓⣀⣠⣴⣿⣿⣿⡿⢛⣩⣴⣾⣿⡿⠿⠛⠋⠉⠁⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠈⠙⠻⢿⣿⣦⣅⠘⠿⠋⠁⢈⠟⣫⣿⣿⠿⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⠃⠐⡄⠀⠁⡺⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
                   ))
         (longest-line (apply #'max (mapcar #'length banner))))
    (put-text-property
     (point)
     (dolist (line banner (point))
       (insert (+doom-dashboard--center
                +doom-dashboard--width
                (concat line (make-string (max 0 (- longest-line (length line))) 32)))
               "\n"))
     'face 'doom-dashboard-banner)))

(setq +doom-dashboard-ascii-banner-fn #'kyo/my-shit-is-always-greater)

(custom-set-faces!
  '(doom-dashboard-banner :foreground "#9FE573" :background "#000000" :weight bold)
  '(doom-dashboard-loaded :foreground "#9FE573" :background "#000000" :weight bold))
#+end_src

#+begin_src emacs-lisp :tangle config.el
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-shortmenu)

(add-hook! '+doom-dashboard-functions :append
  (insert "\n" (+doom-dashboard--center +doom-dashboard--width "@kyonax_on_tech")))

(defun kyo/my-shit-is-always-greater ()
  (let* ((banner '(
                   "                                                             "
                   "                         ███████████      █████              "
                   "                     █████████████████████████               "
                   "                  ███████████████████████████                "
                   "                █████████████████████████████                "
                   "               ████████████       ████████████               "
                   "              ██████████          █████████████              "
                   "              █████████          ██████████████              "
                   "             ██████████         █████ ██████████             "
                   "             ██████████       ██████  ██████████             "
                   "             ██████████      ██████   ██████████             "
                   "             ██████████     █████     ██████████             "
                   "             ██████████   ██████      ██████████             "
                   "             ██████████  ██████       ██████████             "
                   "             ██████████ █████         ██████████             "
                   "              ██████████████         ██████████              "
                   "              █████████████         ███████████              "
                   "               ████████████       ████████████               "
                   "                █████████████████████████████                "
                   "                ███████████████████████████                  "
                   "               █████████████████████████                     "
                   "             ██████     ████████████                         "
                   "                                                             "
                   "                        zerønet labs                         "
                   "                     Cristian D. Moreno                      "
                   "                                                             "
                   "                                                             "))
         (longest-line (apply #'max (mapcar #'length banner))))
    (put-text-property
     (point)
     (dolist (line banner (point))
       (insert (+doom-dashboard--center
                +doom-dashboard--width
                (concat line
                        (make-string (max 0 (- longest-line (length line))) 32)))
               "\n"))
     'face 'doom-dashboard-banner)))

(setq +doom-dashboard-ascii-banner-fn #'kyo/my-shit-is-always-greater)

(custom-set-faces!
  '(doom-dashboard-banner :foreground "#9FE573" :background "#000000" :weight bold)
  '(doom-dashboard-loaded :foreground "#9FE573" :background "#000000" :weight bold))
#+end_src

**** THEME
Set the default theme of Emacs with the next elisp code. See some ~theme~ options:
- *doom-monokai-pro*
- *doom-monokai-spectrum*
- *gruber-darker*

Load a new Theme using the Keybinding ~"SPC h t"~ and select the Theme.
#+begin_src emacs-lisp :tangle config.el
(setq doom-theme 'doom-monokai-spectrum)
(map! :leader
      :desc "Load new theme" "h t" #'counsel-load-theme)
#+end_src

**** TREEMASCS PACKAGE
Setup the ~treemacs~ package used as a File Manager.
#+begin_src emacs-lisp :tangle config.el
(use-package treemacs
  :config
  (setq evil-treemacs-state-cursor t
        treemacs-show-cursor t
        treemacs-width 39))
#+end_src

**** UI
Set Default configuration for the UI of the Emacs Editor.
#+begin_src emacs-lisp :tangle config.el
(setq display-line-numbers-type 'relative
      display-line-numbers-mode t
      line-number-mode t)
#+end_src

**** LSP-UI
LSP UI Defalts
#+begin_src emacs-lisp :tangle config.el
(setq lsp-ui-doc-show-with-cursor t)
(setq lsp-ui-doc-delay 0.2)

(map! :leader
      :desc "Show LSP UI Doc"
      "c d" #'lsp-ui-doc-show)
#+end_src

*** EDITOR MODEs
**** SCSS-MODE
Setup the ~scss-mode~ package to use it on all SCSS files with LSP and linters.
#+begin_src emacs-lisp :tangle config.el
(use-package scss-mode
  :mode ("\\.scss\\'" . scss-mode)
  :hook ((scss-mode . lsp-deferred)
         (scss-mode . flycheck-mode)
         (scss-mode . whitespace-mode)
         (scss-mode . prettier-js-mode))
  :config
  (setq css-indent-offset 2))
#+end_src

**** CSS-MODE
Setup the ~css-mode~ package to use it on all CSS files with LSP and linters.
#+begin_src emacs-lisp :tangle config.el
(use-package css-mode
  :mode ("\\.css\\'" . css-mode)
  :hook ((css-mode . lsp-deferred)
         (css-mode . flycheck-mode)
         (css-mode . whitespace-mode)
         (css-mode . prettier-js-mode))
  :config
  (setq css-indent-offset 2))
#+end_src

**** JS2-MODE
Setup the ~js2-mode~ package to use it on all the Javascript Files.
#+begin_src emacs-lisp :tangle config.el
(defun kyo/js2-mode-setup ()
  (js2-minor-mode))

(use-package js2-mode
  :mode (("\\.plugin\\.js\\'" . js2-mode)
         ("\\.js\\'" . js2-mode)
         ("\\.jsx\\'" . js2-mode)
         ("\\.mjs\\'" . js2-mode)
         ("\\.cjs\\'" . js2-mode)
         ("\\.es6\\'" . js2-mode))
  :interpreter ("javascript" . js2-mode)
  :hook ((js2-mode . lsp-deferred)
         (js2-mode . kyo/js2-mode-setup)))
#+end_src

**** TYPESCRIPT-MODE
Setup the ~typescript-mode~ package to use it on all the TS Files.
#+begin_src emacs-lisp :tangle config.el
(use-package typescript-mode
  :mode (("\\.ts\\'" . typescript-mode)
         ("\\.tsx\\'" . typescript-mode))
  :hook (typescript-mode . lsp-deferred))
 #+end_src

**** JSON-MODE
Setup the ~json-mode~ package to use it on all the Json Files.
#+begin_src emacs-lisp :tangle config.el
(use-package json-mode
  :mode ("\\.json\\'" . json-mode))
#+end_src

**** LSP-MODE
Setting up the ccls (C/C++/Objective-C language server) to use with ~lsp~.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(after! ccls
  (setq ccls-executable "C:/ProgramData/chocolatey/bin/ccls.exe")
  (set-lsp-priority! 'ccls 0))
#+end_src

Setup the ~lsp-mode~ package to use it on the main languages that I work with.
#+begin_src emacs-lisp :tangle no
(defun kyo/lsp-mode-setup ()
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
  (lsp-headerline-breadcrumb-mode)
  (lsp-ui-sideline-toggle-symbols-info))
#+end_src

#+begin_src emacs-lisp :tangle config.el
(defun kyo/lsp-mode-setup ()
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols))
  (lsp-headerline-breadcrumb-mode))

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :hook ((js2-mode . lsp-mode)
         (typescript-mode . lsp-mode)
         (web-mode . lsp-mode)
         (lsp-mode . kyo/lsp-mode-setup))

  :init
  (setq lsp-keymap-prefix "C-c l")
  :config
  (lsp-enable-which-key-integration t))

(use-package lsp-ui
  :hook ((js2-mode . lsp-ui-mode)
         (typescript-mode . lsp-ui-mode)
         (web-mode . lsp-ui-mode)))
#+end_src

#+begin_src emacs-lisp :tangle no
(setq lsp-solargraph-use-bundler t)

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration '(ruby-mode . "ruby"))
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection '("solargraph" "stdio"))
                    :major-modes '(ruby-mode)
                    :priority -1
                    :server-id 'ruby-ls)))
#+end_src

**** ORG-MODE
Setup the ~org-mode~ package to use the magick on my Org Files.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "personal-linux") "config.el" "no")
(defvar my-org-todo-keywords
  '("TODO(t)"    ; A task that is ready to be tackled
    "CODE(m)"    ; Coding Tasks
    "TEST(c)"    ; Blog writing assignments
    "DEVELOP(d)" ; Things to develop
    "MEET(5)"    ; A Meeting
    "PROYECT(p)" ; A project that contains other tasks
    "REVIEW(r)"  ; A project that contains other tasks
    "WAIT(w)"    ; Something is holding up this task
    "|"          ; Separates active from inactive states
    "DONE(d)"    ; Task has been completed
    "CANCELLED(c)")  ; Task has been cancelled
  "List of Org todo keywords for the sequence.")
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "work-mac") "config.el" "no")
(defvar my-org-todo-keywords
  '("TODO(t)"        ; A task that is ready to be tackled
    "CODE(m)"        ; Coding Tasks
    "TEST(s)"        ; Blog writing assignments
    "DEVELOP(o)"     ; Things to develop
    "MEET(5)"        ; A Meeting
    "PROYECT(p)"     ; A project that contains other tasks
    "REVIEW(r)"      ; A project that contains other tasks
    "WAIT(w)"        ; Something is holding up this task
    "|"              ; Separates active from inactive states
    "DONE(d)"        ; Task has been completed
    "CANCELLED(c)")  ; Task has been cancelled
  "List of Org todo keywords for the sequence.")
#+end_src

#+begin_src emacs-lisp :tangle config.el
(after! org
  (setq org-directory "~/org"
        org-ellipsis " ▼ "
        org-hide-emphasis-markers t))

(after! org-superstar
  (setq org-superstar-headline-bullets-list '("" "" "" "󰺕" "󰻂" "󰪥" "󰻃")
        org-superstar-itembullet-alist '((?+ . ?➤)
                                         (?- . ?✦))))

(after! org
  (setq org-todo-keywords `((sequence ,@my-org-todo-keywords))))
#+end_src

***** AGENDA
Setup the ~org-agenda~ package to use it with the Org Mode. The Agenda is a node roam file used in the ~brain~ roam.
#+begin_src emacs-lisp :tangle config.el
(setq org-agenda-block-separator 175)
#+end_src

*Agenda File Linux Config:*
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "personal-linux") "config.el" "no")
(after! org
  (setq org-agenda-files '("~/.brain.d/roam-nodes/20240912084617-agenda.org")))

(setq org-agenda-custom-commands
      '(("v" "A better agenda view"
         ((tags "PRIORITY=\"A\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "High-priority unfinished tasks:")))
          (tags "PRIORITY=\"B\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Medium-priority unfinished tasks:")))
          (tags "PRIORITY=\"C\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Low-priority unfinished tasks:")))
          (tags "homea"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "[#A] Home Daily Tasks:")))
          (tags "homeb"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "[#B] Home Wed-Fri Day Tasks:")))
          (tags "homec"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "[#C] Home Weekly Tasks:")))
          (tags "health"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Family Health:")))
          (tags "work"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Work Tasks:")))
          (tags "kyo"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Kyonax's Projects:")))
          (tags "event"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Important Events:")))
          (tags "meeting"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Important Meetings:")))
          (agenda "")
          (alltodo "")))))
#+end_src

*Agenda File Windows Config:*
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "work-mac") "config.el" "no")
(after! org
  (setq org-agenda-files '("~/.brain.d/roam-nodes/2025-02-13-$S-work_s_org_agenda_file.org")))

(setq org-agenda-custom-commands
      '(("v" "A better agenda view"
         ((tags "PRIORITY=\"A\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "High-priority unfinished tasks:")))
          (tags "PRIORITY=\"B\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Medium-priority unfinished tasks:")))
          (tags "PRIORITY=\"C\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Low-priority unfinished tasks:")))
          (tags "madison-reed"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Tasks for Maritz:")))
          (tags "agile-engine"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Tasks for Softtek:")))
          (tags "dot-com"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Tasks for Shoptron:")))
          (tags "work"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Work Tasks:")))
          (tags "meeting"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done 'wait))
                 (org-agenda-overriding-header "Important Meetings:")))
          (agenda "")
          (alltodo "")))))
#+end_src

***** AUTO-TANGLE
Setup the ~org-auto-tangle~ to Org Files when the document is saved, this functionality works when the ~#+auto_tangle: t~ option is set at the top of the file.
#+begin_src emacs-lisp :tangle config.el
(defun kyo/tangle-on-save ()
  "If the current Org buffer has the auto_tangle tag, execute all code blocks and tangle the file."
  (when (and (derived-mode-p 'org-mode)
             ;; Check for the #+auto_tangle: t tag in the file
             (save-excursion
               (goto-char (point-min))
               (re-search-forward "^#\\+auto_tangle:[ \t]*t" nil t)))
    (org-babel-tangle)))

;; Add kyo/tangle-on-save to the after-save-hook for Org mode buffers only.
(add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'after-save-hook #'kyo/tangle-on-save nil t)))

(defun kyo/insert-auto-tangle-tag ()
  "Insert auto-tangle tag in a literate config."
  (interactive)
  (evil-org-open-below 1)
  (insert "#+auto_tangle: t ")
  (evil-force-normal-state))

(map! :leader
      :desc "Insert auto_tangle tag" "i a" #'kyo/insert-auto-tangle-tag)
#+end_src

***** BABEL
Setup the ~org-babel-languages~ to evaluate all this languages from the org code blocks.
#+begin_src emacs-lisp :tangle config.el
(org-babel-do-load-languages
 'org-babel-load-languages
 '((typescript . t)
   (javascript . t)
   (emacs-lisp . t)
   (js . t)
   (json . t)
   (php . t)
   (web . t)
   ))

(setq org-babel-command:typescript "npx -p typescript -- tsc")
(setq org-confirm-babel-evaluate nil)
#+end_src

***** FANCY PRIORITIEs
Setup the ~org-fancy-priorities~ package to stylize the priorities of the Org Files.
#+begin_src emacs-lisp :tangle config.el
(use-package org-fancy-priorities
  :ensure t
  :hook
  (org-mode . org-fancy-priorities-mode)
  (org-mode . org-superstar-mode)
  :config
  (setq org-fancy-priorities-list '("" "󱡞" "󰝨")
   org-priority-faces
   '((?A :foreground "#ff6c6b" :weight regular)
     (?B :foreground "#98be65" :weight regular)
     (?C :foreground "#c678dd" :weight regular))))
#+end_src
***** ROAM
Setup the ~org-roam~ package to use the ~brain~ notes.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "personal-linux") "config.el" "no")
(defvar my-org-roam-capture-templates
  '(
    ("d" "default" plain "%?"
     :if-new (file+head "%<%Y-%m-%d-$S>-${slug}.org"
                        "#+title: ${title}\n")
     :unnarrowed t)
    ("s" "Not Time Stamp File" plain "%?"
     :if-new (file+head "${slug}.org"
                        "#+title: ${title}\n")
     :unnarrowed t)
    ("f" "New Feature Azure DevOps" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeTemplate.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: ${title}\n#+DESCRIPTION: %^{Description}\n#+FILETAGS: %^{File Tags}\n#+AUTHOR: %^{Author}\n")
     :unnarrowed t)
    ("i" "New Sentinel Inspection" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeSentinelInspection.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: Kyonax's Daily Sentinel Inspection ~ %<%d/%m/%Y> \n")
     :unnarrowed t)
    ("v" "New Invoice" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeInvoice.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: Invoice ${Client Name}\n#+AUTHOR: %^{Author | Cristian D. Moreno - Kyonax}\n")
     :unnarrowed t)
    ("p" "New PBI Azure DevOps" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeProject.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: ${title}\n#+DESCRIPTION: %^{Description}\n#+FILETAGS: %^{File Tags}\n#+AUTHOR: %^{Author}\n")
     :unnarrowed t))
  "My custom Org Roam personal capture templates.")
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "work-mac") "config.el" "no")
(defvar my-org-roam-capture-templates
  '(
    ("d" "default" plain "%?"
     :if-new (file+head "%<%Y-%m-%d-$S>-${slug}.org"
                        "#+title: ${title}\n")
     :unnarrowed t)
    ("s" "Not Time Stamp File" plain "%?"
     :if-new (file+head "${slug}.org"
                        "#+title: ${title}\n")
     :unnarrowed t)
    ("f" "New Feature Azure DevOps" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeTemplate.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: ${title}\n#+DESCRIPTION: %^{Description}\n#+FILETAGS: %^{File Tags}\n#+AUTHOR: %^{Author}\n")
     :unnarrowed t)
    ("i" "New Sentinel Inspection" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeSentinelInspection.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: Kyonax's Daily Sentinel Inspection ~ %<%d/%m/%Y> \n")
     :unnarrowed t)
    ("v" "New Invoice" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeInvoice.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: Invoice ${Client Name}\n#+AUTHOR: %^{Author | Cristian D. Moreno - Kyonax}\n")
     :unnarrowed t)
    ("p" "New PBI Azure DevOps" plain
     (file "~/.brain.d/roam-nodes/templates/NEWNodeProject.org")
     :if-new (file+head "%<%Y-%m-%d-%S>-${slug}.org"
                        "#+TITLE: ${title}\n#+DESCRIPTION: %^{Description}\n#+FILETAGS: %^{File Tags}\n#+AUTHOR: %^{Author}\n")
     :unnarrowed t))
  "My custom Org Roam personal capture templates.")
#+end_src

#+begin_src emacs-lisp :tangle config.el
(after! org-roam
  :ensure t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (setq org-roam-directory "~/.brain.d/roam-nodes")
  (setq org-roam-dailies-directory "~/.brain.d/agenda")
  (setq org-roam-completion-everywhere t)
  (setq org-roam-capture-templates `,my-org-roam-capture-templates))
#+end_src

- *Keybindings Org Roam Dailies*
| COMMAND                            | DESCRIPTION                                 | KEYBINDING |
|------------------------------------+---------------------------------------------+------------|
| org-roam-dailies-capture-yesterday | /Create a daily roam node for Yesterday/      | SPC n D Y  |
| org-roam-dailies-capture-yesterday | /Create a daily roam node for Today/          | SPC n D H  |
| org-roam-dailies-capture-tomorrow  | /Create a daily roam node for Tomorrow/       | SPC n D T  |
| org-roam-dailies-capture-date      | /Create a daily roam node using Calendar/     | SPC n D C  |
| org-roam-dailies-goto-date         | /Find a daily roam node from a specific Date/ | SPC n e d  |

#+begin_src emacs-lisp :tangle config.el
(map! :leader
      (:prefix ("n D" . "Create Roam Nodes")
       :desc "Daily Nodes - Yesterday" "Y" #'org-roam-dailies-capture-yesterday
       :desc "Daily Nodes - Today" "H" #'org-roam-dailies-capture-today
       :desc "Daily Nodes - Calendar" "C" #'org-roam-dailies-capture-date
       :desc "Daily Nodes - Tomorrow" "T" #'org-roam-dailies-capture-tomorrow))
#+end_src

#+begin_src emacs-lisp :tangle config.el
(map! :leader
      (:prefix ("n e" . "Find Roam Nodes")
       :desc "Daily Nodes - Date" "d" #'org-roam-dailies-goto-date
       :desc "Daily Nodes - Yesterday" "Y" #'org-roam-dailies-goto-yesterday
       :desc "Daily Nodes - Today" "H" #'org-roam-dailies-goto-today
       :desc "Daily Nodes - Tomorrow" "T" #'org-roam-dailies-goto-tomorrow))
#+end_src

- *Websocket Config:*
#+begin_src emacs-lisp :tangle config.el
(use-package! websocket
    :after org-roam)
(use-package! org-roam-ui
    :after org
    :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src

**** RAINBOW-MODE
Set the ~rainbow-mode~ package to displays the actual color for any hex value color.
#+begin_src emacs-lisp :tangle config.el
(define-globalized-minor-mode global-rainbow-mode rainbow-mode
  (lambda ()
    (when (not (memq major-mode
                (list 'org-agenda-mode)))
     (rainbow-mode 1))))
(global-rainbow-mode 1 )

(add-hook! 'rainbow-mode-hook
  (hl-line-mode (if rainbow-mode -1 +1)))
#+end_src

**** WEB-MODE
Setup the ~web-mode~ package to use it on all html template files.
#+begin_src emacs-lisp :tangle config.el
(defun kyo/web-mode-setup ()
  (setq web-mode-enable-current-element-highlight t)
  (setq web-mode-enable-current-column-highlight t)
  (setq web-mode-block-padding 2))

(use-package web-mode
  :mode (("\\.html\\'" . web-mode)
         ("\\.html\\.twig\\'" . web-mode))
  :hook (web-mode . kyo/web-mode-setup))
#+end_src

**** FLYCHECK
Add =flycheck= with eslint for JSX/TSX.
#+begin_src emacs-lisp :tangle config.el
(use-package flycheck
  :init (global-flycheck-mode)
  :hook ((js2-mode . flycheck-mode)
         (typescript-mode . flycheck-mode)))
#+end_src

**** WHITESPACE-MODE
Setup the ~whitespace-mode~ package to use it on the main languages that I work with.
#+begin_src emacs-lisp :tangle config.el
(use-package whitespace-mode
  :hook ((js2-mode . whitespace-mode)
         (typescript-mode . whitespace-mode)
         (web-mode . whitespace-mode)
         (php-mode . whitespace-mode)
         (json-mode . whitespace-mode)))
#+end_src

**** PRETTIER (CLI)
Setup Prettier CLI to format ~js2-mode~, ~typescript-mode~, ~web-mode~, and ~json-mode~ files before saving.
Disable LSP formatting and indentation to avoid conflicts.

#+begin_src emacs-lisp :tangle config.el
(use-package prettier-js
  :hook ((js2-mode . prettier-js-mode)
         (typescript-mode . prettier-js-mode)
         (json-mode . prettier-js-mode)
         (web-mode . prettier-js-mode)))

(defun kyo/run-prettier ()
  "Format the current file using the Prettier CLI if available."
  (interactive)
  (when (and buffer-file-name
             (string-match-p
              "\\.\\(js\\|jsx\\|ts\\|tsx\\|mjs\\|cjs\\|es6\\|json\\|html?\\)\\'"
              buffer-file-name))
    (let* ((project-root (locate-dominating-file buffer-file-name "node_modules"))
           (local-prettier (and project-root (expand-file-name "node_modules/.bin/prettier" project-root)))
           (prettier-bin (or (and local-prettier (file-executable-p local-prettier) local-prettier)
                             (executable-find "prettier"))))
      (when prettier-bin
        (shell-command-to-string
         (format "%s --write %s"
                 (shell-quote-argument prettier-bin)
                 (shell-quote-argument buffer-file-name)))
        (revert-buffer t t t)))))
#+end_src

*** USER DEFAULTs
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "personal-linux") "config.el" "no")
(setq user-full-name "Cristian D. Moreno - Kyonax"
      user-mail-address "kyonax.corp@gmail.com")
#+end_src


#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-profile") "work-mac") "config.el" "no")
(setq user-full-name "Cristian D. Moreno - Agile Engine"
      user-mail-address "cristian.moreno@agileengine.com")
#+end_src

*** DIRED PACKAGE
Setup the ~dired~ file manager, new keybindings, implementation of ~peep-dired~, and general configurations.

- *Keybindings to open Dired*
| COMMAND    | DESCRIPTION                        | KEYBINDING |
|------------+------------------------------------+------------|
| dired      | /Open dired file manager/            | SPC d d    |
| dired-jump | /Jump to current directory in dired/ | SPC d j    |

- *Keybindings basic Dired*
| COMMAND                | DESCRIPTION                                 | KEYBINDING |
|------------------------+---------------------------------------------+------------|
| dired-view-file        | /View file in dired/                          | SPC d v    |
| dired-up-directory     | /Go up in directory tree/                     | h          |
| dired-find-file        | /Go down in directory tree (or open if file)/ | l          |
| dired-next-line        | /Move down to next line/                      | j          |
| dired-previous-line    | /Move up to previous line/                    | k          |
| dired-mark             | /Mark file at point/                          | m          |
| dired-unmark           | /Unmark file at point/                        | u          |
| dired-do-copy          | /Copy current file or marked files/           | C          |
| dired-do-rename        | /Rename current file or marked files/         | R          |
| dired-hide-details     | /Toggle detailed listings on/off/             | (          |
| dired-git-info-mode    | /Toggle git information on/off/               | )          |
| dired-create-directory | /Create new empty directory/                  | +          |
| dired-diff             | /Compare file at point with another/          | =          |
| dired-subtree-toggle   | /Toggle viewing subtree at point/             | TAB        |

- *Keybindings regexp Dired*
| COMMAND                 | DESCRIPTION                | KEYBINDING |
|-------------------------+----------------------------+------------|
| dired-mark-files-regexp | /Mark files using regex/     | % m        |
| dired-do-copy-regexp    | /Copy files using regex/     | % C        |
| dired-do-rename-regexp  | /Rename files using regex/   | % R        |
| dired-mark-files-regexp | /Mark all files using regex/ | * %        |

- *Keybindings sudo Dired*
| COMMAND         | DESCRIPTION                      | KEYBINDING |
|-----------------+----------------------------------+------------|
| dired-do-chgrp  | /Change the group of marked files/ | g G        |
| dired-do-chmod  | /Change the mode of marked files/  | M          |
| dired-do-chown  | /Change the owner of marked files/ | O          |
| dired-do-rename | /Rename file or all marked files/  | R          |

- *Keybindings peep-dired-mode Dired*
| COMMAND              | DESCRIPTION                              | KEYBINDING |
|----------------------+------------------------------------------+------------|
| peep-dired           | /Toggle previews within dired/             | SPC d p    |
| peep-dired-next-file | /Move to next file in peep-dired-mode/     | j          |
| peep-dired-prev-file | /Move to previous file in peep-dired-mode/ | k          |

#+begin_src emacs-lisp :tangle config.el
(map! :leader
      (:prefix ("d" . "dired")
       :desc "Open dired" "d" #'dired
       :desc "Dired jump to current" "j" #'dired-jump)
      (:after dired
              (:map dired-mode-map
               :desc "Peep-dired image previews" "d p" #'peep-dired
               :desc "Dired view file"           "d v" #'dired-view-file)))

(evil-define-key 'normal dired-mode-map
  (kbd "M-RET") 'dired-display-file
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file
  (kbd "m") 'dired-mark
  (kbd "t") 'dired-toggle-marks
  (kbd "u") 'dired-unmark
  (kbd "C") 'dired-do-copy
  (kbd "D") 'dired-do-delete
  (kbd "J") 'dired-goto-file
  (kbd "M") 'dired-do-chmod
  (kbd "O") 'dired-do-chown
  (kbd "P") 'dired-do-print
  (kbd "R") 'dired-do-rename
  (kbd "T") 'dired-do-touch
  (kbd "Y") 'dired-copy-filenamecopy-filename-as-kill
  (kbd "Z") 'dired-do-compress
  (kbd "+") 'dired-create-directory
  (kbd "-") 'dired-do-kill-lines
  (kbd "% l") 'dired-downcase
  (kbd "% m") 'dired-mark-files-regexp
  (kbd "% u") 'dired-upcase
  (kbd "* %") 'dired-mark-files-regexp
  (kbd "* .") 'dired-mark-extension
  (kbd "* /") 'dired-mark-directories
  (kbd "; d") 'epa-dired-do-decrypt
  (kbd "; e") 'epa-dired-do-encrypt)
;; With dired-open plugin, you can launch external programs for certain extensions
;; For example, I set all .png files to open in 'sxiv' and all .mp4 files to open in 'mpv'
(setq dired-open-extensions '(("gif" . "sxiv")
                              ("jpg" . "sxiv")
                              ("png" . "sxiv")
                              ("mkv" . "mpv")
                              ("mp4" . "mpv")))

(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
#+end_src

Creation and usage of the Dired trash can. Don't forget to create a ~symlink~ to the home directory.
#+begin_src emacs-lisp :tangle config.el
(setq delete-by-moving-to-trash t
      trash-directory "~/.local/share/Trash/files/")
#+end_src

- *Open Dired Config*
#+begin_src emacs-lisp :tangle config.el
(defun kyo/open-directory (dir)
  "Open the specified directory DIR in Dired mode."
  (interactive "DChoose directory: ") ; Prompt for directory
  (dired dir))
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "os") "config.el" "no")
(defun shoptron ()
  "Open the Shoptron main Directory"
  (interactive)
  (kyo/open-directory "/plinkw:dockware@127.0.0.1:~/html"))

(defun shtheme ()
  "Open the ShoptronTheme main Directory"
  (interactive)
  (kyo/open-directory "/plinkw:dockware@127.0.0.1:~/html/custom/plugins/ShoptronTheme"))

(defun shconfigurator ()
  "Open the ShoptronConfiurator main Directory"
  (interactive)
  (kyo/open-directory "/plinkw:dockware@127.0.0.1:~/html/custom/plugins/ShoptronConfigurator"))
#+end_src

*** GPTEL
Setup the ~gptel~ package to use LLMs on Emacs.
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(gptel-make-openai "xAI"
  :host "api.x.ai"
  :key (shell-command-to-string (format "gopass show sub/private_key/xai"))
  :endpoint "/v1/chat/completions"
  :stream t
  :models '(grok-3-latest))

;; OPTIONAL configuration
(setq
 gptel-model   'grok-3-latest
 gptel-backend
 (gptel-make-openai "xAI"
   :host "api.x.ai"
   :key (shell-command-to-string (format "gopass show sub/private_key/xai"))
   :endpoint "/v1/chat/completions"
   :stream t
   :models '(;; xAI now only offers `grok-beta` as of the time of this writing
             grok-3-latest)))
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "linux") "config.el" "no")
(gptel-make-openai "xAI"
  :host "api.x.ai"
  :key (shell-command-to-string (format "pass show private_key/xai | tr -d '\n'"))
  :endpoint "/v1/chat/completions"
  :stream t
  :models '(grok-3-latest))

;; OPTIONAL configuration
(setq
 gptel-model   'grok-3-latest
 gptel-backend
 (gptel-make-openai "xAI"           ;Any name you want
   :host "api.x.ai"
   :key (shell-command-to-string (format "pass show private_key/xai | tr -d '\n'"))              ;can be a function that returns the key
   :endpoint "/v1/chat/completions"
   :stream t
   :models '(;; xAI now only offers `grok-beta` as of the time of this writing
             grok-3-latest)))

(add-hook 'gptel-post-stream-hook 'gptel-auto-scroll)
#+end_src

**** DIRECTIVEs CONFIG

- *Default Work - OLD:*
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(setq! gptel-directives '(
 (default . "Test 32")
 (studying . "")
 (documentation . "")
 (manual . "")))
#+end_src

- *Directives Linux - Freelance*:
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "linux") "config.el" "no")
(setq! gptel-directives '(
 (default . "")
 (documentation . "")
 (manual . "")))
#+end_src


*** IVY PACKAGE
Setup the ~ivy~ package for Emacs, generic completion mechanism. Implementing posframe for ivy, and the configuration documentation.

- ~ivy-posframe-display-functions-alist~ -- sets the display position for specific programs
- ~ivy-posframe-height-alist~ -- sets the height of the list displayed for specific programs

Available positions for the posframe implementation ~ivy-posframe-display-functions-alist~:
- ~ivy-posframe-display-at-frame-center~
- ~ivy-posframe-display-at-window-center~
- ~ivy-posframe-display-at-frame-bottom-left~
- ~ivy-posframe-display-at-window-bottom-left~
- ~ivy-posframe-display-at-frame-bottom-window-center~
- ~ivy-posframe-display-at-point~
- ~ivy-posframe-display-at-frame-top-center~

=NOTE:= If the setting for ~ivy-posframe-display~ is set to ~nil~ (false), anything that is set to ~ivy-display-function-fallback~ will just default to their normal position in Doom Emacs (usually a bottom split).  However, if this is set to ~t~ (true), then the fallback position will be centered in the window.

#+begin_src emacs-lisp :tangle config.el
(setq ivy-posframe-display-functions-alist
      '((swiper                     . ivy-posframe-display-at-point)
        (complete-symbol            . ivy-posframe-display-at-point)
        (counsel-M-x                . ivy-display-function-fallback)
        (counsel-esh-history        . ivy-posframe-display-at-window-center)
        (counsel-describe-function  . ivy-display-function-fallback)
        (counsel-describe-variable  . ivy-display-function-fallback)
        (counsel-find-file          . ivy-display-function-fallback)
        (counsel-recentf            . ivy-display-function-fallback)
        (counsel-register           . ivy-posframe-display-at-frame-bottom-window-center)
        (dmenu                      . ivy-posframe-display-at-frame-top-center)
        (nil                        . ivy-posframe-display))
      ivy-posframe-height-alist
      '((swiper . 20)
        (dmenu . 20)
        (t . 10)))
(ivy-posframe-mode 1) ; 1 enables posframe-mode, 0 disables it.
#+end_src

- *Keybindings Ivy*
| COMMAND         | DESCRIPTION         | KEYBINDING |
|-----------------+---------------------+------------|
| ivy-push-view   | /Push the Ivy view/   | SPC v p    |
| ivy-switch-view | /Switch the Ivy view/ | SPC v s    |

#+begin_src emacs-lisp :tangle config.el
(map! :leader
      (:prefix ("v" . "Ivy")
       :desc "Ivy push view" "p" #'ivy-push-view
       :desc "Ivy switch view" "s" #'ivy-switch-view))
#+end_src

*** LATEX PACKAGE
Setup the ~latext~ package to use with org.
#+begin_src emacs-lisp :tangle config.el
(with-eval-after-load 'ox-latex
  (add-to-list 'org-latex-classes
               '("org-plain-latex"
                 "\\documentclass{article}
                [NO-DEFAULT-PACKAGES]
                [PACKAGES]
                \\newcommand{\\checkbox}{\\text{[ ]}} % Define \checkbox
                \\newcommand{\\checkedbox}{\\text{[X]}} % Define \checkedbox
                [EXTRA]"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))

(after! org
  ;; Minted config for much better syntax highlightig to src blocks.
  (setq
   org-latex-listings 'minted
   ;; minted calls the pygmentize process and thus needs shell escaping
   org-latex-pdf-process
   '("xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
     "xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
     "xelatex -shell-escape -interaction nonstopmode -output-directory %o %f")
   ;; NOTE I don't actually add minted to the package list, I'll just \usepackage it when needed

   ;;(setq org-latex-pdf-process
   ;;'("latexmk -f -pdf %f")) ; Doesn't work with pdflatex
   ;; Margins
   ;;(add-to-list 'org-latex-packages-alist '("a4paper,margin=1.1in" "geometry"))

   ;; Add 'colorlinks' option to hyperrref, its much prettier
   org-latex-hyperref-template
   "\\hypersetup{
 pdfauthor={%a},
 pdftitle={%t},
 pdfkeywords={%k},
 pdfsubject={%d},
 pdfcreator={%c},
 pdflang={%L},
 colorlinks=true,
 linkcolor={cyan}
}"
   ;; page break after TOC
   org-latex-toc-command "\\tableofcontents\n\\pagebreak\n\n")
  ;; org-latex-minted-options '(("bgcolor" "{white!98!black}"))
  ;; org-latex-minted-options '(("bgcolor" "\\color{white!96!black}"))
  ;; In case I configured hyperref in a separate latex preamble
  ;;(setq org-latex-hyperref-template ""))
  (add-hook! 'org-roam-buffer-prepare-hook
    (setq display-line-numbers nil)))


(setq org-highlight-latex-and-related '(native))

(require 'org-src)
(add-to-list 'org-src-block-faces '("latex" (:inherit default :extend t)))

;; Define the custom checklist symbols in LaTeX
(defun my-org-latex-checklist-filter (text backend info)
  "Replace Org checklist symbols with custom LaTeX symbols."
  (when (org-export-derived-backend-p backend 'latex)
    (let ((text (replace-regexp-in-string "\\[ \\]" "\\\\checkbox" text))
          (text (replace-regexp-in-string "\\[X\\]" "\\\\checkedbox" text)))
      text)))

;; Add the custom filter to the export process
(add-hook 'org-export-filter-final-output-functions
          'my-org-latex-checklist-filter)
#+end_src

*** PDF VIEWER
Configure the ~pdf~ viewer.
#+begin_src emacs-lisp :tangle config.el
(use-package pdf-view
  :hook (pdf-tools-enabled . pdf-view-midnight-minor-mode)
  :hook (pdf-tools-enabled . hide-mode-line-mode)
  :config
  (setq pdf-view-midnight-colors '("#888888" . "#111111")))
#+end_src

*** TRAMP
Setup the ~tramp~ package to be used on Windows.
#+BEGIN_SRC emacs-lisp :tangle config.el
(setq password-cache-expiry nil)
#+END_SRC

- *Tramp Windows Config*
#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "windows") "config.el" "no")
(use-package tramp
  :config
  (add-to-list 'tramp-methods `("plinkw"
                                (tramp-login-program "plink")
                                (tramp-login-args (("-ssh")
                                                   (,(format
                                                      "dockware@127.0.0.1 -pw dockware"))))
                                (tramp-remote-shell "/bin/sh"))))

(when (eq window-system 'w32)
  (setq tramp-default-method "plink")
  (when (and (not (string-match putty-directory (getenv "PATH")))
	     (file-directory-p putty-directory))
    (setenv "PATH" (concat putty-directory ";" (getenv "PATH")))
    (add-to-list 'exec-path putty-directory)))
#+end_src

*** RUBY SET-UP
#+begin_src emacs-lisp :tangle no
(load (expand-file-name "modules/editor.el" doom-user-dir))
(load (expand-file-name "modules/misc.el" doom-user-dir))
(load (expand-file-name "modules/ruby.el" doom-user-dir))
(load (expand-file-name "modules/ruby-autocomplete.el" doom-user-dir))
(load (expand-file-name "modules/term.el" doom-user-dir))
(load (expand-file-name "modules/git.el" doom-user-dir))
(load (expand-file-name "modules/lsp.el" doom-user-dir))
(load (expand-file-name "modules/org.el" doom-user-dir))
(load (expand-file-name "modules/autocomplete.el" doom-user-dir))
#+end_src

** init.el
These are *Doom Emacs’ core modules*. I can enable or disable them simply by uncommenting them, and add custom flags when needed to fine-tune their behavior.

#+begin_quote
ℹ Press =SPC h d h= (or =C-h d h= for non-Vim users) to open Doom’s documentation. There, you’ll find a full index of available modules and the flags they support.
️
You can also hover over a module name or flag and press =K= (=C-c c k= for non-Vim users) to view its documentation, or =gd= (=C-c c d=) to jump directly to its source directory.
#+end_quote

*Header File:*
#+begin_src emacs-lisp :tangle init.el
;;; init.el -*- lexical-binding: t; -*-

(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row
#+end_src

*** COMPLETION
#+begin_src emacs-lisp :tangle init.el

       :completion
       ;;company                        ; the ultimate code completion backend
       (corfu +orderless +icons)        ; complete with cap(f), cape and a flying feather!
       ;;(helm +childframe +icons)      ; the *other* search engine for love and life
       ;;ido                            ; the other *other* search engine...
       (ivy +icons +fuzzy +childframe +prescient)  ; a search engine for love and life
       ;;vertico                        ; the search engine of the future
#+end_src

*** UI
#+begin_src emacs-lisp :tangle init.el

       :ui
       deft                ; notational velocity for Emacs
       doom                ; what makes DOOM look the way it does
       doom-dashboard      ; a nifty splash screen for Emacs
       doom-quit           ; DOOM quit-message prompts when you quit Emacs
       ;;(emoji +unicode)  ; 🙂
       hl-todo             ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       indent-guides       ; highlighted indent columns
       (ligatures +extras) ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline            ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints             ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;smooth-scroll     ; So smooth you won't believe it's not butter
       ;;tabs              ; a tab bar for Emacs
       (treemacs +lsp)     ; a project drawer, like neotree but cooler
       unicode             ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe     ; fringe tildes to mark beyond EOB
       (window-select +numbers)       ; visually switch windows
       workspaces          ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing
#+end_src

*** EDITOR
#+begin_src emacs-lisp :tangle init.el

       :editor
       (evil +everywhere)  ; come to the dark side, we have cookies
       file-templates      ; auto-snippets for empty files
       fold                ; (nigh) universal code folding
       (format +onsave +lsp)    ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       multiple-cursors    ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       rotate-text         ; cycle region at point between text candidates
       snippets            ; my elves. They type so I don't have to
       (whitespace +guess +trim)  ; a butler for your whitespace
       word-wrap           ; soft wrapping with language-aware indent
#+end_src

*** EMACS
#+begin_src emacs-lisp :tangle init.el

       :emacs
       (dired +dirvish +icons)      ; making dired pretty [functional]
       electric            ; smarter, keyword-based electric-indent
       ;;eww               ; the internet is gross
       (ibuffer +icons)    ; interactive buffer management
       undo       ; persistent, smarter undo for your inevitable mistakes
       tramp               ; remote files at your arthritic fingertips
       vc                  ; version-control and Emacs, sitting in a tree
#+end_src

*** TERM
#+begin_src emacs-lisp :tangle init.el

       :term
       eshell              ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm               ; the best terminal emulation in Emacs
#+end_src

*** CHECKERs
#+begin_src emacs-lisp :tangle init.el

       :checkers
       (syntax +childframe +flymake +icons)  ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make
#+end_src

*** TOOLs
#+begin_src emacs-lisp :tangle init.el

       :tools
       ;;ansible
       biblio              ; Writes a PhD for you (citation needed)
       ;;collab            ; buffers with friends
       debugger            ; FIXME stepping through code, to help you add bugs
       ;;direnv
       (docker +lsp +tree-sitter)
       editorconfig        ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       (lookup +dictionary +docsets)              ; navigate your code and its documentation
       llm                 ; when I said you needed friends, I didn't mean...
       (lsp +peek)         ; M-x vscode
       (magit +forge)      ; a git porcelain for Emacs
       make                ; run make tasks from Emacs
       pass                ; password manager for nerds
       pdf                 ; pdf enhancements
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       tree-sitter         ; syntax and parsing, sitting in a tree...
       upload              ; map local to remote projects via ssh/ftp
#+end_src

*** OS
#+begin_src emacs-lisp :tangle init.el

       :os
       tty                 ; improve the terminal Emacs experience
#+end_src

#+begin_src emacs-lisp :tangle (if (string= (org-babel-ref-resolve "get-os-type") "mac") "init.el" "no")
        (:if (featurep :system 'macos) macos)  ; improve compatibility with macOS
#+end_src

*** LANG
#+begin_src emacs-lisp :tangle init.el

       :lang
       ;;ada               ; In strong typing we (blindly) trust
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       (cc +lsp)           ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       data                ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       (emacs-lisp +lsp)   ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       (json +lsp +tree-sitter)         ; At least it ain't XML
       ;;janet             ; Fun fact: Janet is me!
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       (javascript +lsp +tree-sitter)   ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       (latex +cdlatex +fold +lsp)               ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       (markdown +grip +tree-sitter)            ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org +crypt +gnuplot +hugo +journal +dragndrop +present)               ; organize your plain life in plain text
       ;;php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;graphviz          ; diagrams for confusing yourself even more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       (rest +jq)                ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       (sh +lsp)           ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       (swift +lsp +tree-sitter)               ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       (web +lsp +tree-sitter)               ; the tubes
       (yaml +lsp +tree-sitter)              ; JSON, but readable
       ;;zig               ; C, but simpler
#+end_src

*** EMAIL
#+begin_src emacs-lisp :tangle init.el
       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)
#+end_src

*** APP
#+begin_src emacs-lisp :tangle init.el

       :app
       calendar
       ;;emms
       everywhere          ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)          ; emacs as an RSS reader
#+end_src

*** CONFIG
#+begin_src emacs-lisp :tangle init.el

       :config
       literate
       (default +gnupg +bindings +smartparens))
#+end_src

* CUSTOM FUNCTIONs
** CREATE INVOICE NUMBER
#+begin_src emacs-lisp :tangle no
(defun kyo/create-invoice-number (&optional dir invoice-paths)
  "Search for invoice files in DIR or INVOICE-PATHS, count them,
   and return the next invoice number formatted with the current date.

   DIR is the directory to search for invoice files. If not provided,
   it defaults to the current directory.

   INVOICE-PATHS is a list of file paths to check for invoice files.
   If provided, it is used instead of searching a directory.

   The next invoice number is based on the quantity of matched files
   with 'invoice' in their names."
  (let* ((current-year (format-time-string "%Y"))
         (current-month (format-time-string "%m"))
         (current-day (format-time-string "%d"))
         (invoice-count 0))

    ;; Count invoice files
    (if invoice-paths
        (dolist (path invoice-paths)
          (when (and (stringp path)
                     (string-match-p "invoice" (file-name-nondirectory path))
                     (file-exists-p path))
            (setq invoice-count (1+ invoice-count))))
      (let ((files (directory-files (or dir default-directory) t "\\(invoice\\|-invoice\\)")))
        (dolist (file files)
          (when (string-match-p "invoice" (file-name-nondirectory file))
            (setq invoice-count (1+ invoice-count))))))

    ;; Calculate and format the next invoice number
    (let* ((next-number (1+ invoice-count))
           (formatted-number (format "%02d" next-number)))
      (concat current-year current-month current-day "-" formatted-number))))
#+end_src
